<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Topic 8 Bootstrapping MLR Model | STA 321 E-pack: Advanced Statistics</title>
  <meta name="description" content="The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Topic 8 Bootstrapping MLR Model | STA 321 E-pack: Advanced Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Topic 8 Bootstrapping MLR Model | STA 321 E-pack: Advanced Statistics" />
  
  <meta name="twitter:description" content="The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Cheng Peng" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-linear-regression-model.html"/>
<link rel="next" href="simple-logistic-regression-model.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<center><li><a href="./"><font color = "darkred"><b>STA 321 E-Pack: Advanced Statistics</b></font></a><br><font color = "navy">Cheng Peng</font></li></center>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#why-this-e-pack"><i class="fa fa-check"></i><b>1.1</b> Why This E-Pack?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#components-statistical-reports"><i class="fa fa-check"></i><b>1.2</b> Components Statistical Reports</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#a.-introduction"><i class="fa fa-check"></i>A. Introduction</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#b.-materials"><i class="fa fa-check"></i>B. Materials</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#c.-methodology"><i class="fa fa-check"></i>C. Methodology</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#d.-results-and-conclusions"><i class="fa fa-check"></i>D. Results and Conclusions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#e.-general-discussion"><i class="fa fa-check"></i>E. General Discussion</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#f.-references-if-any"><i class="fa fa-check"></i>F. References (if any)</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#g.-appendices-if-any"><i class="fa fa-check"></i>G. Appendices (if any)</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#basics-of-rstudio"><i class="fa fa-check"></i><b>1.3</b> Basics of RStudio</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#rstudio-gui"><i class="fa fa-check"></i><b>1.3.1</b> RStudio GUI</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#rmarkdown"><i class="fa fa-check"></i><b>1.3.2</b> RMarkdown</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#collaborative-platforms"><i class="fa fa-check"></i><b>1.4</b> Collaborative Platforms</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#rpubs"><i class="fa fa-check"></i><b>1.4.1</b> RPubs</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#github-repository"><i class="fa fa-check"></i><b>1.4.2</b> GitHub Repository</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#github"><i class="fa fa-check"></i><b>1.5</b> Github</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#what-is-github"><i class="fa fa-check"></i><b>1.5.1</b> What is Github?</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#getting-started-with-github"><i class="fa fa-check"></i><b>1.5.2</b> Getting Started with GitHub</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html"><i class="fa fa-check"></i><b>2</b> Data Input and Output in R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#built-in-data"><i class="fa fa-check"></i><b>2.1</b> Built-in Data</a></li>
<li class="chapter" data-level="2.2" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#loading-external-data-sets"><i class="fa fa-check"></i><b>2.2</b> Loading External Data Sets</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#preparing-r-workspace"><i class="fa fa-check"></i><b>2.2.1</b> Preparing R Workspace</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#setting-up-working-directory"><i class="fa fa-check"></i><b>2.2.2</b> Setting-up Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#read-common-files-into-r"><i class="fa fa-check"></i><b>2.3</b> Read Common Files into R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#read-txt-files-with-read.table"><i class="fa fa-check"></i><b>2.3.1</b> Read TXT files with read.table()</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#data-values-separated-by-special-symbol"><i class="fa fa-check"></i><b>2.4</b> Data Values Separated By Special Symbol</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#importing-a-csv-into-r"><i class="fa fa-check"></i><b>2.4.1</b> Importing a CSV into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#import-sas-spss-and-other-data-sets-into-r"><i class="fa fa-check"></i><b>2.5</b> Import SAS, SPSS, and Other Data Sets into R</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#import-spss-files-into-r"><i class="fa fa-check"></i><b>2.5.1</b> Import SPSS Files into R</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#mport-stata-files-into-r"><i class="fa fa-check"></i><b>2.5.2</b> mport Stata Files into R</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#import-systat-files-into-r"><i class="fa fa-check"></i><b>2.5.3</b> Import Systat Files into R</a></li>
<li class="chapter" data-level="2.5.4" data-path="data-input-and-output-in-r.html"><a href="data-input-and-output-in-r.html#import-sas-files-into-r"><i class="fa fa-check"></i><b>2.5.4</b> Import SAS Files into R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html"><i class="fa fa-check"></i><b>3</b> Base R Graphical Functions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html#r-graphic-devices"><i class="fa fa-check"></i><b>3.1</b> R Graphic Devices</a></li>
<li class="chapter" data-level="3.2" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html#plotting-with-base-graphics-plot"><i class="fa fa-check"></i><b>3.2</b> Plotting with Base Graphics: <code>plot()</code></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html#outer-and-inner-margins"><i class="fa fa-check"></i><b>3.2.1</b> Outer and Inner Margins</a></li>
<li class="chapter" data-level="3.2.2" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html#simple-multi-panel-plots"><i class="fa fa-check"></i><b>3.2.2</b> Simple multi-panel Plots</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="base-r-graphical-functions.html"><a href="base-r-graphical-functions.html#making-our-own-colors"><i class="fa fa-check"></i><b>3.3</b> Making Our Own Colors</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html"><i class="fa fa-check"></i><b>4</b> Effective Data Preparation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#data-set-description"><i class="fa fa-check"></i><b>4.1</b> Data Set Description</a></li>
<li class="chapter" data-level="4.2" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#base-r-commands-for-data-management"><i class="fa fa-check"></i><b>4.2</b> Base R Commands for Data Management</a></li>
<li class="chapter" data-level="4.3" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#working-with-scientific-notations"><i class="fa fa-check"></i><b>4.3</b> Working with Scientific Notations</a></li>
<li class="chapter" data-level="4.4" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#the-ifelse-function"><i class="fa fa-check"></i><b>4.4</b> The <strong>ifelse()</strong> Function</a></li>
<li class="chapter" data-level="4.5" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#the-cut-function"><i class="fa fa-check"></i><b>4.5</b> The <strong>cut()</strong> Function</a></li>
<li class="chapter" data-level="4.6" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#with-and-within-functions"><i class="fa fa-check"></i><b>4.6</b> <strong>with()</strong> and <strong>within()</strong> Functions</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#the-with-function"><i class="fa fa-check"></i><b>4.6.1</b> The <strong>with()</strong> Function</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#the-merge-function---table-joins"><i class="fa fa-check"></i><b>4.7</b> The <strong>merge()</strong> Function - Table Joins</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#inner-join"><i class="fa fa-check"></i><b>4.7.1</b> Inner Join</a></li>
<li class="chapter" data-level="4.7.2" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#left-join"><i class="fa fa-check"></i><b>4.7.2</b> Left Join</a></li>
<li class="chapter" data-level="4.7.3" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#right-join"><i class="fa fa-check"></i><b>4.7.3</b> Right Join</a></li>
<li class="chapter" data-level="4.7.4" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#full-outer-join"><i class="fa fa-check"></i><b>4.7.4</b> Full (outer) Join</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#subsetting-data-frame"><i class="fa fa-check"></i><b>4.8</b> Subsetting Data Frame</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#subsetting-by-columns"><i class="fa fa-check"></i><b>4.8.1</b> Subsetting by Columns</a></li>
<li class="chapter" data-level="4.8.2" data-path="effective-data-preparation.html"><a href="effective-data-preparation.html#subsetting-by-rows"><i class="fa fa-check"></i><b>4.8.2</b> Subsetting by Rows</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Bootstrap Confidence Intervals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#basic-idea-of-bootstrap-method."><i class="fa fa-check"></i><b>5.1</b> Basic Idea of Bootstrap Method.</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#random-sample-from-population"><i class="fa fa-check"></i><b>5.1.1</b> Random Sample from Population</a></li>
<li class="chapter" data-level="5.1.2" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#bootstrap-sampling-and-bootstrap-sampling-distribution"><i class="fa fa-check"></i><b>5.1.2</b> Bootstrap Sampling and Bootstrap Sampling Distribution</a></li>
<li class="chapter" data-level="5.1.3" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#relationship-between-two-estimated-sampling-distributions"><i class="fa fa-check"></i><b>5.1.3</b> Relationship between Two Estimated Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#bootstrap-confidence-intervals-1"><i class="fa fa-check"></i><b>5.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="5.3" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#bootstrap-confidence-interval-of-correlation-coefficient"><i class="fa fa-check"></i><b>5.3</b> Bootstrap Confidence Interval of Correlation Coefficient</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#bootstrapping-data-set"><i class="fa fa-check"></i><b>5.3.1</b> Bootstrapping Data Set</a></li>
<li class="chapter" data-level="5.3.2" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#confidence-interval-of-coefficient-correlation"><i class="fa fa-check"></i><b>5.3.2</b> Confidence Interval of Coefficient Correlation</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#problem-set"><i class="fa fa-check"></i><b>5.4</b> Problem Set</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#data-set-description-1"><i class="fa fa-check"></i><b>5.4.1</b> Data Set Description</a></li>
<li class="chapter" data-level="5.4.2" data-path="bootstrap-confidence-intervals.html"><a href="bootstrap-confidence-intervals.html#problems"><i class="fa fa-check"></i><b>5.4.2</b> Problems</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html"><i class="fa fa-check"></i><b>6</b> Bootstrapping SLR</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#data-set-and-practical-questions"><i class="fa fa-check"></i><b>6.1</b> Data Set and Practical Questions</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#data-description"><i class="fa fa-check"></i><b>6.1.1</b> Data Description</a></li>
<li class="chapter" data-level="6.1.2" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#practical-question"><i class="fa fa-check"></i><b>6.1.2</b> Practical Question</a></li>
<li class="chapter" data-level="6.1.3" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>6.1.3</b> Exploratory Data Analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#simple-linear-regression-review"><i class="fa fa-check"></i><b>6.2</b> Simple Linear Regression: Review</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#structure-and-assumptions-of-simple-linear-regression-model"><i class="fa fa-check"></i><b>6.2.1</b> Structure and Assumptions of Simple Linear Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#fitting-slr-to-data"><i class="fa fa-check"></i><b>6.3</b> Fitting SLR to Data</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#parametric-slr"><i class="fa fa-check"></i><b>6.3.1</b> Parametric SLR</a></li>
<li class="chapter" data-level="6.3.2" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#bootstrap-regression"><i class="fa fa-check"></i><b>6.3.2</b> Bootstrap Regression</a></li>
<li class="chapter" data-level="6.3.3" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#concluding-remarks"><i class="fa fa-check"></i><b>6.3.3</b> Concluding Remarks</a></li>
<li class="chapter" data-level="6.3.4" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#bootstrap-residual-method"><i class="fa fa-check"></i><b>6.3.4</b> Bootstrap Residual Method</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#data-set-selection-for-project-one"><i class="fa fa-check"></i><b>6.4</b> Data Set Selection for Project One</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#data-set-requirements"><i class="fa fa-check"></i><b>6.4.1</b> Data Set Requirements</a></li>
<li class="chapter" data-level="6.4.2" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#web-sites-with-data-sets"><i class="fa fa-check"></i><b>6.4.2</b> Web Sites with Data Sets</a></li>
<li class="chapter" data-level="6.4.3" data-path="bootstrapping-slr.html"><a href="bootstrapping-slr.html#analysis-and-writing-components"><i class="fa fa-check"></i><b>6.4.3</b> Analysis and Writing Components</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html"><i class="fa fa-check"></i><b>7</b> Multiple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#the-structure-of-mlr"><i class="fa fa-check"></i><b>7.1</b> The structure of MLR</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#assumptions-based-on-the-above-special-form."><i class="fa fa-check"></i><b>7.1.1</b> Assumptions based on the above special form.</a></li>
<li class="chapter" data-level="7.1.2" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#potential-violations"><i class="fa fa-check"></i><b>7.1.2</b> Potential Violations</a></li>
<li class="chapter" data-level="7.1.3" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#variable-types"><i class="fa fa-check"></i><b>7.1.3</b> Variable types</a></li>
<li class="chapter" data-level="7.1.4" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#dummy-and-discrete-numerical-explanatory-variables"><i class="fa fa-check"></i><b>7.1.4</b> Dummy and discrete numerical explanatory variables</a></li>
<li class="chapter" data-level="7.1.5" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#interpretation-of-regression-coefficients-1"><i class="fa fa-check"></i><b>7.1.5</b> Interpretation of Regression Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#model-building"><i class="fa fa-check"></i><b>7.2</b> Model building</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#data-structure-sample-size-and-preparation-for-mlr"><i class="fa fa-check"></i><b>7.2.1</b> Data structure, sample size, and preparation for MLR</a></li>
<li class="chapter" data-level="7.2.2" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#candidate-models-and-residual-diagnostics"><i class="fa fa-check"></i><b>7.2.2</b> Candidate models and residual diagnostics</a></li>
<li class="chapter" data-level="7.2.3" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#significant-test-goodness-of-fit-and-variable-selection"><i class="fa fa-check"></i><b>7.2.3</b> Significant test, goodness-of-fit, and Variable selection</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#case-study--factors-that-impact-the-house-sale-prices"><i class="fa fa-check"></i><b>7.3</b> Case Study -Factors That Impact the House Sale Prices</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#data-description-1"><i class="fa fa-check"></i><b>7.3.1</b> Data Description</a></li>
<li class="chapter" data-level="7.3.2" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#practical-question-1"><i class="fa fa-check"></i><b>7.3.2</b> Practical Question</a></li>
<li class="chapter" data-level="7.3.3" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#exploratory-data-analysis-1"><i class="fa fa-check"></i><b>7.3.3</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="7.3.4" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#fitting-mlr-to-data"><i class="fa fa-check"></i><b>7.3.4</b> Fitting MLR to Data</a></li>
<li class="chapter" data-level="7.3.5" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#summary-of-the-model"><i class="fa fa-check"></i><b>7.3.5</b> Summary of the model</a></li>
<li class="chapter" data-level="7.3.6" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#discussions"><i class="fa fa-check"></i><b>7.3.6</b> Discussions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="multiple-linear-regression-model.html"><a href="multiple-linear-regression-model.html#written-assignment"><i class="fa fa-check"></i><b>7.4</b> Written Assignment</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html"><i class="fa fa-check"></i><b>8</b> Bootstrapping MLR Model</a>
<ul>
<li class="chapter" data-level="8.1" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#bootstrap-method-revisited"><i class="fa fa-check"></i><b>8.1</b> Bootstrap Method Revisited</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#pdf-vs-cdf"><i class="fa fa-check"></i><b>8.1.1</b> <code>pdf</code> vs <code>CDF</code></a></li>
<li class="chapter" data-level="8.1.2" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#comparing-two-distributions"><i class="fa fa-check"></i><b>8.1.2</b> Comparing Two Distributions</a></li>
<li class="chapter" data-level="8.1.3" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#empirical-distribution-and-cdf"><i class="fa fa-check"></i><b>8.1.3</b> Empirical Distribution and CDF</a></li>
<li class="chapter" data-level="8.1.4" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#relationship-between-fx-and-f_nx"><i class="fa fa-check"></i><b>8.1.4</b> Relationship between <span class="math inline">\(F(x)\)</span> and <span class="math inline">\(F_n(X)\)</span></a></li>
<li class="chapter" data-level="8.1.5" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#why-bootstrap-procedure-works"><i class="fa fa-check"></i><b>8.1.5</b> Why Bootstrap Procedure Works?</a></li>
<li class="chapter" data-level="8.1.6" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#a-bigger-picture"><i class="fa fa-check"></i><b>8.1.6</b> A Bigger Picture</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#other-resampling-methods"><i class="fa fa-check"></i><b>8.2</b> Other Resampling Methods</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#jackknif-resampling"><i class="fa fa-check"></i><b>8.2.1</b> Jackknif Resampling</a></li>
<li class="chapter" data-level="8.2.2" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#jackknife-for-predictive-sum-of-squares-press"><i class="fa fa-check"></i><b>8.2.2</b> Jackknife for Predictive Sum of Squares (PRESS)</a></li>
<li class="chapter" data-level="8.2.3" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#some-comments-on-jackknife"><i class="fa fa-check"></i><b>8.2.3</b> Some Comments on Jackknife</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#parametric-linear-regression-model"><i class="fa fa-check"></i><b>8.3</b> Parametric Linear Regression Model</a></li>
<li class="chapter" data-level="8.4" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#bootstrap-cases-boot.c"><i class="fa fa-check"></i><b>8.4</b> Bootstrap Cases (BOOT.C)</a></li>
<li class="chapter" data-level="8.5" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#bootstrap-residuals-boot.r"><i class="fa fa-check"></i><b>8.5</b> Bootstrap Residuals (BOOT.R)</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#fitted-model"><i class="fa fa-check"></i><b>8.5.1</b> Fitted Model</a></li>
<li class="chapter" data-level="8.5.2" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#residual-bootstrap-samples"><i class="fa fa-check"></i><b>8.5.2</b> Residual Bootstrap Samples</a></li>
<li class="chapter" data-level="8.5.3" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#implementation-of-residual-bootstrap-regression"><i class="fa fa-check"></i><b>8.5.3</b> Implementation of Residual Bootstrap Regression</a></li>
<li class="chapter" data-level="8.5.4" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#combining-all-inferential-statistics"><i class="fa fa-check"></i><b>8.5.4</b> Combining All Inferential Statistics</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#discussions-on-model-reporting"><i class="fa fa-check"></i><b>8.6</b> Discussions on Model Reporting</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#some-concluding-remarks"><i class="fa fa-check"></i><b>8.7</b> Some Concluding Remarks</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#key-elements-in-storytelling"><i class="fa fa-check"></i><b>8.7.1</b> Key Elements in Storytelling</a></li>
<li class="chapter" data-level="8.7.2" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#title-and-heading-in-statistics-report"><i class="fa fa-check"></i><b>8.7.2</b> Title and Heading in Statistics Report</a></li>
<li class="chapter" data-level="8.7.3" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#regression-modeling-and-reporting"><i class="fa fa-check"></i><b>8.7.3</b> Regression Modeling and Reporting</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="bootstrapping-mlr-model.html"><a href="bootstrapping-mlr-model.html#modeling-assignment"><i class="fa fa-check"></i><b>8.8</b> Modeling Assignment</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html"><i class="fa fa-check"></i><b>9</b> Simple Logistic Regression Model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#simple-binary-logistic-regression"><i class="fa fa-check"></i><b>9.1</b> Simple Binary Logistic Regression</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#the-model-structure"><i class="fa fa-check"></i><b>9.1.1</b> The Model Structure</a></li>
<li class="chapter" data-level="9.1.2" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#interpretation-of-regression-coefficients-2"><i class="fa fa-check"></i><b>9.1.2</b> Interpretation of Regression Coefficients</a></li>
<li class="chapter" data-level="9.1.3" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#use-of-simple-logistic-regression-model"><i class="fa fa-check"></i><b>9.1.3</b> Use of Simple Logistic Regression Model</a></li>
<li class="chapter" data-level="9.1.4" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#parameter-estimation"><i class="fa fa-check"></i><b>9.1.4</b> Parameter Estimation</a></li>
<li class="chapter" data-level="9.1.5" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#model-assumptions-and-diagnostics"><i class="fa fa-check"></i><b>9.1.5</b> Model Assumptions and Diagnostics</a></li>
<li class="chapter" data-level="9.1.6" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#concluding-remarks-1"><i class="fa fa-check"></i><b>9.1.6</b> Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#a-case-study"><i class="fa fa-check"></i><b>9.2</b> A Case Study</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#data-and-variable-descriptions"><i class="fa fa-check"></i><b>9.2.1</b> Data and Variable Descriptions</a></li>
<li class="chapter" data-level="9.2.2" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#clinical-question"><i class="fa fa-check"></i><b>9.2.2</b> Clinical Question</a></li>
<li class="chapter" data-level="9.2.3" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#building-the-simple-logistic-regression"><i class="fa fa-check"></i><b>9.2.3</b> Building the Simple Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#conclusion"><i class="fa fa-check"></i><b>9.3</b> Conclusion</a></li>
<li class="chapter" data-level="9.4" data-path="simple-logistic-regression-model.html"><a href="simple-logistic-regression-model.html#analysis-assignment"><i class="fa fa-check"></i><b>9.4</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html"><i class="fa fa-check"></i><b>10</b> Multiple Logistic Regression Model</a>
<ul>
<li class="chapter" data-level="10.1" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#multiple-logistic-regression-model-1"><i class="fa fa-check"></i><b>10.1</b> Multiple Logistic Regression Model</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#data-requirements-sources-layout-and-cleansing"><i class="fa fa-check"></i><b>10.1.1</b> Data Requirements: Sources, Layout, and Cleansing</a></li>
<li class="chapter" data-level="10.1.2" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#issues-of-predictor-variables-and-variable-inspection-transformation"><i class="fa fa-check"></i><b>10.1.2</b> Issues of Predictor Variables and Variable Inspection-Transformation</a></li>
<li class="chapter" data-level="10.1.3" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#estimation-and-interpretation-of-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Estimation and Interpretation of Regression Coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#building-blocks-for-predictive-performance"><i class="fa fa-check"></i><b>10.2</b> Building Blocks for Predictive Performance</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#understanding-the-performance-of-medical-diagnostics"><i class="fa fa-check"></i><b>10.2.1</b> Understanding the Performance of Medical Diagnostics</a></li>
<li class="chapter" data-level="10.2.2" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#performance-metrics-used-in-clinical-trials"><i class="fa fa-check"></i><b>10.2.2</b> Performance Metrics Used in Clinical Trials:</a></li>
<li class="chapter" data-level="10.2.3" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#remarks"><i class="fa fa-check"></i><b>10.2.3</b> Remarks</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#case-study"><i class="fa fa-check"></i><b>10.3</b> Case Study</a></li>
<li class="chapter" data-level="10.4" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#data-and-variable-descriptions-1"><i class="fa fa-check"></i><b>10.4</b> Data and Variable Descriptions</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#research-question"><i class="fa fa-check"></i><b>10.4.1</b> Research Question</a></li>
<li class="chapter" data-level="10.4.2" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#exploratory-analysis"><i class="fa fa-check"></i><b>10.4.2</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="10.4.3" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#building-the-multiple-logistic-regression-model"><i class="fa fa-check"></i><b>10.4.3</b> Building the Multiple Logistic Regression Model</a></li>
<li class="chapter" data-level="10.4.4" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#final-model-1"><i class="fa fa-check"></i><b>10.4.4</b> Final Model</a></li>
<li class="chapter" data-level="10.4.5" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#summary-and-conclusion"><i class="fa fa-check"></i><b>10.4.5</b> Summary and Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="multiple-logistic-regression-model.html"><a href="multiple-logistic-regression-model.html#analysis-assignment-1"><i class="fa fa-check"></i><b>10.5</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html"><i class="fa fa-check"></i><b>11</b> Predictive Modeling with Logistic Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#cross-validation-in-predictive-modeling"><i class="fa fa-check"></i><b>11.1</b> Cross-Validation in Predictive Modeling</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#the-logic-of-the-three-way-split"><i class="fa fa-check"></i><b>11.1.1</b> The Logic of the Three-way Split</a></li>
<li class="chapter" data-level="11.1.2" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#cross-validation-cv"><i class="fa fa-check"></i><b>11.1.2</b> Cross-validation (CV)</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#predictive-performance-measures"><i class="fa fa-check"></i><b>11.2</b> Predictive Performance Measures</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#error-based-measures"><i class="fa fa-check"></i><b>11.2.1</b> Error-based Measures</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#measuring-global-performance---roc-curve"><i class="fa fa-check"></i><b>11.3</b> Measuring Global Performance - ROC Curve</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#roc-curve"><i class="fa fa-check"></i><b>11.3.1</b> ROC Curve</a></li>
<li class="chapter" data-level="11.3.2" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#area-under-the-curve-auc"><i class="fa fa-check"></i><b>11.3.2</b> Area Under The Curve (AUC)</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#case-study---diabetes-prediction-with-logistic-regression"><i class="fa fa-check"></i><b>11.4</b> Case Study - Diabetes Prediction with Logistic Regression</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#data-and-variable-descriptions-2"><i class="fa fa-check"></i><b>11.4.1</b> Data and Variable Descriptions</a></li>
<li class="chapter" data-level="11.4.2" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#research-question-1"><i class="fa fa-check"></i><b>11.4.2</b> Research Question</a></li>
<li class="chapter" data-level="11.4.3" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#exploratory-analysis-1"><i class="fa fa-check"></i><b>11.4.3</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="11.4.4" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#standizing-numerical-predictor-variables"><i class="fa fa-check"></i><b>11.4.4</b> Standizing Numerical Predictor Variables</a></li>
<li class="chapter" data-level="11.4.5" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#data-split---training-and-testing-data"><i class="fa fa-check"></i><b>11.4.5</b> Data Split - Training and Testing Data</a></li>
<li class="chapter" data-level="11.4.6" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#best-model-identification"><i class="fa fa-check"></i><b>11.4.6</b> Best Model Identification</a></li>
<li class="chapter" data-level="11.4.7" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#roc-analysis---global-performance"><i class="fa fa-check"></i><b>11.4.7</b> ROC Analysis - Global Performance</a></li>
<li class="chapter" data-level="11.4.8" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#summary-and-conclusion-1"><i class="fa fa-check"></i><b>11.4.8</b> Summary and Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="predictive-modeling-with-logistic-regression.html"><a href="predictive-modeling-with-logistic-regression.html#analysis-assignment-2"><i class="fa fa-check"></i><b>11.5</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html"><i class="fa fa-check"></i><b>12</b> Poison Regression Modeling</a>
<ul>
<li class="chapter" data-level="12.1" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#linear-regression-models"><i class="fa fa-check"></i><b>12.1</b> Linear Regression Models</a></li>
<li class="chapter" data-level="12.2" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#binary-logistic-regression-model"><i class="fa fa-check"></i><b>12.2</b> Binary Logistic Regression Model</a></li>
<li class="chapter" data-level="12.3" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#poisson-regression-models"><i class="fa fa-check"></i><b>12.3</b> Poisson Regression Models</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#assumptions-of-the-poisson-regression-model"><i class="fa fa-check"></i><b>12.3.1</b> Assumptions of the Poisson Regression Model</a></li>
<li class="chapter" data-level="12.3.2" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#structure-of-poisson-regression-model-for-counts"><i class="fa fa-check"></i><b>12.3.2</b> Structure of Poisson Regression Model for Counts</a></li>
<li class="chapter" data-level="12.3.3" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#poisson-models-for-rates"><i class="fa fa-check"></i><b>12.3.3</b> Poisson Models for Rates</a></li>
<li class="chapter" data-level="12.3.4" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#estimation-of-regression-coefficients-and-goodness-of-fit"><i class="fa fa-check"></i><b>12.3.4</b> Estimation of Regression Coefficients and Goodness-of-fit</a></li>
<li class="chapter" data-level="12.3.5" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#data-set-layout"><i class="fa fa-check"></i><b>12.3.5</b> Data Set Layout</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#case-study-modeling-lung-cancer-rates-in-four-cities-of-denmark---part-i"><i class="fa fa-check"></i><b>12.4</b> Case Study: Modeling Lung Cancer Rates in Four Cities of Denmark - Part I</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#poisson-regression-on-cancer-counts"><i class="fa fa-check"></i><b>12.4.1</b> Poisson Regression on Cancer Counts</a></li>
<li class="chapter" data-level="12.4.2" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#poisson-regression-on-rates"><i class="fa fa-check"></i><b>12.4.2</b> Poisson Regression on Rates</a></li>
<li class="chapter" data-level="12.4.3" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#some-graphical-comparison"><i class="fa fa-check"></i><b>12.4.3</b> Some Graphical Comparison</a></li>
<li class="chapter" data-level="12.4.4" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#discussions-and-conclusions"><i class="fa fa-check"></i><b>12.4.4</b> Discussions and Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#concluding-remarks-2"><i class="fa fa-check"></i><b>12.5</b> Concluding Remarks</a></li>
<li class="chapter" data-level="12.6" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#analysis-assignment-3"><i class="fa fa-check"></i><b>12.6</b> Analysis Assignment</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#data-description-2"><i class="fa fa-check"></i><b>12.6.1</b> Data Description</a></li>
<li class="chapter" data-level="12.6.2" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#data-formats-and-loading"><i class="fa fa-check"></i><b>12.6.2</b> Data Formats and Loading</a></li>
<li class="chapter" data-level="12.6.3" data-path="poison-regression-modeling.html"><a href="poison-regression-modeling.html#assignment-instructions"><i class="fa fa-check"></i><b>12.6.3</b> Assignment Instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html"><i class="fa fa-check"></i><b>13</b> Dispersed Poisson Regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#residuals-of-poisson-regression"><i class="fa fa-check"></i><b>13.1</b> Residuals of Poisson Regression</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#pearson-residuals"><i class="fa fa-check"></i><b>13.1.1</b> Pearson Residuals</a></li>
<li class="chapter" data-level="13.1.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#deviance-residuals"><i class="fa fa-check"></i><b>13.1.2</b> Deviance Residuals</a></li>
<li class="chapter" data-level="13.1.3" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#numerical-example"><i class="fa fa-check"></i><b>13.1.3</b> Numerical Example</a></li>
<li class="chapter" data-level="13.1.4" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>13.1.4</b> Goodness-of-fit</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#dispersion-and-dispersed-poisson-regression-model"><i class="fa fa-check"></i><b>13.2</b> Dispersion and Dispersed Poisson Regression Model</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#definition-of-dispersion"><i class="fa fa-check"></i><b>13.2.1</b> Definition of Dispersion</a></li>
<li class="chapter" data-level="13.2.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#quasi-poisson-regression-model"><i class="fa fa-check"></i><b>13.2.2</b> Quasi-Poisson Regression Model</a></li>
<li class="chapter" data-level="13.2.3" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#numerical-example-1"><i class="fa fa-check"></i><b>13.2.3</b> Numerical Example</a></li>
<li class="chapter" data-level="13.2.4" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#summary-and-concluding-remarks"><i class="fa fa-check"></i><b>13.2.4</b> Summary and Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#case-study-i-denmark-cities-lung-cancer-rates"><i class="fa fa-check"></i><b>13.3</b> Case Study I: Denmark Cities Lung Cancer Rates</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#introduction-1"><i class="fa fa-check"></i><b>13.3.1</b> Introduction</a></li>
<li class="chapter" data-level="13.3.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#poisson-regression-on-cancer-counts-1"><i class="fa fa-check"></i><b>13.3.2</b> Poisson Regression on Cancer Counts</a></li>
<li class="chapter" data-level="13.3.3" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#poisson-regression-on-rates-1"><i class="fa fa-check"></i><b>13.3.3</b> Poisson Regression on Rates</a></li>
<li class="chapter" data-level="13.3.4" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#quasi-poisson-rate-model"><i class="fa fa-check"></i><b>13.3.4</b> Quasi-Poisson Rate Model</a></li>
<li class="chapter" data-level="13.3.5" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#final-working-model"><i class="fa fa-check"></i><b>13.3.5</b> Final Working Model</a></li>
<li class="chapter" data-level="13.3.6" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#some-visual-comparisons"><i class="fa fa-check"></i><b>13.3.6</b> Some Visual Comparisons</a></li>
<li class="chapter" data-level="13.3.7" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#discussions-and-conclusions-1"><i class="fa fa-check"></i><b>13.3.7</b> Discussions and Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#case-study-ii---ph.d.-and-mentors-productivity"><i class="fa fa-check"></i><b>13.4</b> Case Study II - Ph.D. and Mentor’s Productivity</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#variable-description"><i class="fa fa-check"></i><b>13.4.1</b> Variable Description</a></li>
<li class="chapter" data-level="13.4.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#research-question-2"><i class="fa fa-check"></i><b>13.4.2</b> Research Question</a></li>
<li class="chapter" data-level="13.4.3" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#data-preparation-and-variable-processing"><i class="fa fa-check"></i><b>13.4.3</b> Data Preparation and Variable Processing</a></li>
<li class="chapter" data-level="13.4.4" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#poison-regression-modeling-1"><i class="fa fa-check"></i><b>13.4.4</b> Poison Regression Modeling</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#section"><i class="fa fa-check"></i><b>13.5</b> </a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#some-visual-comparisons-1"><i class="fa fa-check"></i><b>13.5.1</b> Some Visual Comparisons</a></li>
<li class="chapter" data-level="13.5.2" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#conclusions"><i class="fa fa-check"></i><b>13.5.2</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="dispersed-poisson-regression.html"><a href="dispersed-poisson-regression.html#analysis-assignment-4"><i class="fa fa-check"></i><b>13.6</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html"><i class="fa fa-check"></i><b>14</b> Concepts of Time Series Forecasting</a>
<ul>
<li class="chapter" data-level="14.1" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#types-of-time-series-data"><i class="fa fa-check"></i><b>14.1</b> Types of Time Series Data</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#uncorrelated-data-constant-process-model-random-time-series"><i class="fa fa-check"></i><b>14.1.1</b> Uncorrelated data, constant process model: random time series</a></li>
<li class="chapter" data-level="14.1.2" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#autocorrelated-data"><i class="fa fa-check"></i><b>14.1.2</b> Autocorrelated data</a></li>
<li class="chapter" data-level="14.1.3" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#trend-data"><i class="fa fa-check"></i><b>14.1.3</b> Trend Data</a></li>
<li class="chapter" data-level="14.1.4" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#seasonal-data"><i class="fa fa-check"></i><b>14.1.4</b> Seasonal Data</a></li>
<li class="chapter" data-level="14.1.5" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#nonstationary-data"><i class="fa fa-check"></i><b>14.1.5</b> Nonstationary Data</a></li>
<li class="chapter" data-level="14.1.6" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#atypical-event-outliers"><i class="fa fa-check"></i><b>14.1.6</b> Atypical Event (Outliers)</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#some-technical-terms-and-baseline-forecasting-models"><i class="fa fa-check"></i><b>14.2</b> Some Technical Terms and Baseline Forecasting Models</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#some-definitions"><i class="fa fa-check"></i><b>14.2.1</b> Some Definitions</a></li>
<li class="chapter" data-level="14.2.2" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#baseline-methods"><i class="fa fa-check"></i><b>14.2.2</b> Baseline Methods</a></li>
<li class="chapter" data-level="14.2.3" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#seasonal-naive-method"><i class="fa fa-check"></i><b>14.2.3</b> Seasonal Naive Method</a></li>
<li class="chapter" data-level="14.2.4" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#drift-method"><i class="fa fa-check"></i><b>14.2.4</b> Drift Method</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#accuracy-measures-in-time-series-forecasting"><i class="fa fa-check"></i><b>14.3</b> Accuracy Measures in Time Series Forecasting</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#training-and-testing-data"><i class="fa fa-check"></i><b>14.3.1</b> Training and Testing Data</a></li>
<li class="chapter" data-level="14.3.2" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#forecasting-errors"><i class="fa fa-check"></i><b>14.3.2</b> Forecasting Errors</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#case-study-1"><i class="fa fa-check"></i><b>14.4</b> Case Study</a></li>
<li class="chapter" data-level="14.5" data-path="concepts-of-time-series-forecasting.html"><a href="concepts-of-time-series-forecasting.html#analysis-assignment-5"><i class="fa fa-check"></i><b>14.5</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html"><i class="fa fa-check"></i><b>15</b> Time Series Decomposition</a>
<ul>
<li class="chapter" data-level="15.1" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#classical-decompositions"><i class="fa fa-check"></i><b>15.1</b> Classical Decompositions</a></li>
<li class="chapter" data-level="15.2" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#understanding-the-classical-decomposition-of-time-series"><i class="fa fa-check"></i><b>15.2</b> Understanding the Classical Decomposition of Time Series</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#detect-trend"><i class="fa fa-check"></i><b>15.2.1</b> Detect Trend</a></li>
<li class="chapter" data-level="15.2.2" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#extracting-the-seasonality"><i class="fa fa-check"></i><b>15.2.2</b> Extracting the Seasonality</a></li>
<li class="chapter" data-level="15.2.3" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#extracting-remainder-errors"><i class="fa fa-check"></i><b>15.2.3</b> Extracting Remainder Errors</a></li>
<li class="chapter" data-level="15.2.4" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#reconstruct-the-original-series-compose-new-series"><i class="fa fa-check"></i><b>15.2.4</b> Reconstruct the Original Series / Compose New Series</a></li>
<li class="chapter" data-level="15.2.5" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#decomposing-time-series-with-decompose"><i class="fa fa-check"></i><b>15.2.5</b> Decomposing Time Series with <strong>decompose()</strong></a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#forecasting-with-decomposing"><i class="fa fa-check"></i><b>15.3</b> Forecasting with Decomposing</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#forecasting-additive-models-with-decomposing"><i class="fa fa-check"></i><b>15.3.1</b> Forecasting Additive Models with Decomposing</a></li>
<li class="chapter" data-level="15.3.2" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#concepts-of-seasonal-and-trend-decomposition-using-loess-stl"><i class="fa fa-check"></i><b>15.3.2</b> Concepts of Seasonal and Trend Decomposition Using Loess (STL)</a></li>
<li class="chapter" data-level="15.3.3" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#forecast-with-stl-decomposing"><i class="fa fa-check"></i><b>15.3.3</b> Forecast with STL decomposing</a></li>
<li class="chapter" data-level="15.3.4" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#length-of-time-series"><i class="fa fa-check"></i><b>15.3.4</b> Length of Time Series</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#case-study-2"><i class="fa fa-check"></i><b>15.4</b> Case Study</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#data-description-and"><i class="fa fa-check"></i><b>15.4.1</b> Data description and</a></li>
<li class="chapter" data-level="15.4.2" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#define-time-series-object"><i class="fa fa-check"></i><b>15.4.2</b> Define time series object</a></li>
<li class="chapter" data-level="15.4.3" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#forecasting-with-decomposing-1"><i class="fa fa-check"></i><b>15.4.3</b> Forecasting with Decomposing</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="time-series-decomposition.html"><a href="time-series-decomposition.html#analysis-assignment-6"><i class="fa fa-check"></i><b>15.5</b> Analysis Assignment</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html"><i class="fa fa-check"></i><b>16</b> Exponential Smoothing Methods</a>
<ul>
<li class="chapter" data-level="16.1" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#ets-framework"><i class="fa fa-check"></i><b>16.1</b> ETS Framework</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#exponential-smoothing-methods-1"><i class="fa fa-check"></i><b>16.1.1</b> Exponential Smoothing Methods</a></li>
<li class="chapter" data-level="16.1.2" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#exponential-smoothing-models"><i class="fa fa-check"></i><b>16.1.2</b> Exponential Smoothing Models</a></li>
<li class="chapter" data-level="16.1.3" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#estimation-smoothing-parameters-in-smoothing-models"><i class="fa fa-check"></i><b>16.1.3</b> Estimation Smoothing Parameters in Smoothing Models</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#simple-exponential-smoothing"><i class="fa fa-check"></i><b>16.2</b> Simple Exponential Smoothing</a></li>
<li class="chapter" data-level="16.3" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#holts-smoothing-model-linear-additive-trend"><i class="fa fa-check"></i><b>16.3</b> Holt’s Smoothing Model: Linear (additive) Trend</a></li>
<li class="chapter" data-level="16.4" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#damped-trend-methods"><i class="fa fa-check"></i><b>16.4</b> Damped Trend Methods</a></li>
<li class="chapter" data-level="16.5" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#holt-winters-model-for-trend-and-seasonal-data"><i class="fa fa-check"></i><b>16.5</b> Holt-Winters Model for Trend and Seasonal Data</a></li>
<li class="chapter" data-level="16.6" data-path="exponential-smoothing-methods.html"><a href="exponential-smoothing-methods.html#case-study-3"><i class="fa fa-check"></i><b>16.6</b> Case study</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STA 321 E-pack: Advanced Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bootstrapping-mlr-model" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Topic 8</span> Bootstrapping MLR Model<a href="bootstrapping-mlr-model.html#bootstrapping-mlr-model" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this note, we introduce two versions of bootstrap procedures to generate bootstrap samples to estimate the confidence intervals of the coefficients of the regression model identified in the previous note. We first fit the linear model to the data and then use bootstrap methods to construct the confidence intervals of regression coefficients.</p>
<div id="bootstrap-method-revisited" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Bootstrap Method Revisited<a href="bootstrapping-mlr-model.html#bootstrap-method-revisited" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <strong>bootstrap</strong> is one of the computationally intensive techniques that is now part of the broad umbrella of <strong>nonparametric statistics</strong> that are commonly called <strong>resampling methods</strong>.</p>
<p>We have used this method to construct the confidence interval for a unknown population mean and correlation coefficient of two numerical variables (populations). We also fit bootstrap simple linear regression in two different ways and will use it to build bootstrap MLR.</p>
<p>Based on the limited experience using the bootstrap procedure we had, it is time to look into the resampling technique a little more closer to how and why it works. We will also discuss the implicit assumptions for bootstrap resampling procedures. For ease of illustration, we need to review some concepts learned earlier: probability density function (<code>pdf</code>) and cumulative distribution function (<code>CDF</code>).</p>
<div id="pdf-vs-cdf" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> <code>pdf</code> vs <code>CDF</code><a href="bootstrapping-mlr-model.html#pdf-vs-cdf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(f(x)\)</span> denote the density function of the distribution of the population of interest. The corresponding cumulative distribution is given by</p>
<p><span class="math display">\[
F(x) = \int_{-\infty}^x f(y)dy
\]</span></p>
<p>That is, <span class="math inline">\(F^{\prime}(x) = f(x)\)</span>. The following animated graph illustrates the relationship geometrically.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-92"></span>
<img src="img05/w05-PDFvsCDF.gif" alt="Relationship between Density curve and CDF curve" width="40%" />
<p class="caption">
Figure 8.1: Relationship between Density curve and CDF curve
</p>
</div>
</div>
<div id="comparing-two-distributions" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Comparing Two Distributions<a href="bootstrapping-mlr-model.html#comparing-two-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Next, we use two examples to show how to do visual comparison between distributions.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="bootstrapping-mlr-model.html#cb108-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb108-2"><a href="bootstrapping-mlr-model.html#cb108-2" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="at">length =</span> <span class="dv">200</span>)</span>
<span id="cb108-3"><a href="bootstrapping-mlr-model.html#cb108-3" tabindex="-1"></a><span class="fu">plot</span>(x, <span class="fu">dnorm</span>(x,<span class="dv">5</span>,<span class="dv">1</span>), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb108-4"><a href="bootstrapping-mlr-model.html#cb108-4" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Comparing Two Normal Density Curves&quot;</span>,</span>
<span id="cb108-5"><a href="bootstrapping-mlr-model.html#cb108-5" tabindex="-1"></a>        <span class="at">cex.main =</span> <span class="fl">0.8</span>, <span class="at">col.main =</span> <span class="st">&quot;navy&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-6"><a href="bootstrapping-mlr-model.html#cb108-6" tabindex="-1"></a><span class="fu">lines</span>(x, <span class="fu">dnorm</span>(x, <span class="dv">7</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty =</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-7"><a href="bootstrapping-mlr-model.html#cb108-7" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;right&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;N(5,1)&quot;</span>, <span class="st">&quot;N(7,2)&quot;</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, </span>
<span id="cb108-8"><a href="bootstrapping-mlr-model.html#cb108-8" tabindex="-1"></a>                   <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb108-9"><a href="bootstrapping-mlr-model.html#cb108-9" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb108-10"><a href="bootstrapping-mlr-model.html#cb108-10" tabindex="-1"></a>dist <span class="ot">=</span> <span class="fu">abs</span>(<span class="fu">pnorm</span>(x, <span class="dv">7</span>, <span class="dv">2</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(x,<span class="dv">5</span>,<span class="dv">1</span>))</span>
<span id="cb108-11"><a href="bootstrapping-mlr-model.html#cb108-11" tabindex="-1"></a>max.id <span class="ot">=</span> <span class="fu">which</span>(dist <span class="sc">==</span> <span class="fu">max</span>(dist))</span>
<span id="cb108-12"><a href="bootstrapping-mlr-model.html#cb108-12" tabindex="-1"></a><span class="fu">plot</span>(x, <span class="fu">pnorm</span>(x,<span class="dv">5</span>,<span class="dv">1</span>), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb108-13"><a href="bootstrapping-mlr-model.html#cb108-13" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Comparing Two Normal CDF Curves&quot;</span>,</span>
<span id="cb108-14"><a href="bootstrapping-mlr-model.html#cb108-14" tabindex="-1"></a>        <span class="at">cex.main =</span> <span class="fl">0.8</span>, <span class="at">col.main =</span> <span class="st">&quot;navy&quot;</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-15"><a href="bootstrapping-mlr-model.html#cb108-15" tabindex="-1"></a><span class="fu">lines</span>(x, <span class="fu">pnorm</span>(x, <span class="dv">7</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-16"><a href="bootstrapping-mlr-model.html#cb108-16" tabindex="-1"></a><span class="fu">segments</span>(x[<span class="dv">63</span>],<span class="fu">pnorm</span>(x, <span class="dv">7</span>, <span class="dv">2</span>)[<span class="dv">63</span>], x[<span class="dv">63</span>], <span class="fu">pnorm</span>(x,<span class="dv">5</span>,<span class="dv">1</span>)[<span class="dv">63</span>], <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb108-17"><a href="bootstrapping-mlr-model.html#cb108-17" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(x[<span class="dv">63</span>],<span class="dv">2</span>), <span class="fu">c</span>(<span class="fu">pnorm</span>(x, <span class="dv">7</span>, <span class="dv">2</span>)[<span class="dv">63</span>], <span class="fu">pnorm</span>(x,<span class="dv">5</span>,<span class="dv">1</span>)[<span class="dv">63</span>]), <span class="at">pch=</span><span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.5</span>, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>)</span>
<span id="cb108-18"><a href="bootstrapping-mlr-model.html#cb108-18" tabindex="-1"></a><span class="do">###</span></span>
<span id="cb108-19"><a href="bootstrapping-mlr-model.html#cb108-19" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;right&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;N(5,1)&quot;</span>, <span class="st">&quot;N(7,2)&quot;</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, </span>
<span id="cb108-20"><a href="bootstrapping-mlr-model.html#cb108-20" tabindex="-1"></a>                   <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-93"></span>
<img src="STA321EB_files/figure-html/unnamed-chunk-93-1.png" alt="Comparison between two normal distributions" width="768" />
<p class="caption">
Figure 8.2: Comparison between two normal distributions
</p>
</div>
<p>We can see from the above figure that the <strong>maximum distance between the two CDF curves</strong> (the length of the purple line segment) measures that discrepancy the two distributions.</p>
</div>
<div id="empirical-distribution-and-cdf" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Empirical Distribution and CDF<a href="bootstrapping-mlr-model.html#empirical-distribution-and-cdf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An empirical distribution is a non-parametric estimation of a theoretical distribution based on a random sample taken from the population. Assume that <span class="math inline">\(\{x_1, x_2, x_3, \cdots, x_n \}\)</span> is a random sample taken from a population with CDF <span class="math inline">\(F(x|\theta)\)</span> (<span class="math inline">\(\theta\)</span> is the population parameter). **The empirical distribution of <span class="math inline">\(F(x|\theta)\)</span> based on the given random sample is defined to be</p>
<p><span class="math display">\[
F_n(x) = \frac{\text{number of values in random sample } \le x}{n}
\]</span></p>
<p>For example, let’s look at the emprical distribution based on the toy data set <span class="math inline">\(\{ 1, 1.4, 2.1, 2.5, 5\}\)</span>.</p>
<p><img src="STA321EB_files/figure-html/unnamed-chunk-94-1.png" width="384" style="display: block; margin: auto;" /></p>
</div>
<div id="relationship-between-fx-and-f_nx" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Relationship between <span class="math inline">\(F(x)\)</span> and <span class="math inline">\(F_n(X)\)</span><a href="bootstrapping-mlr-model.html#relationship-between-fx-and-f_nx" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As stated earlier, An empirical distribution, <span class="math inline">\(F_n(x)\)</span>, is used to estimate the theoretical CDF, <span class="math inline">\(F(x)\)</span>. Next, we use several examples to visually check the goodness of the estimation.</p>
<p><img src="STA321EB_files/figure-html/unnamed-chunk-95-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>We can see two general but important facts:</p>
<ol style="list-style-type: decimal">
<li><p>The goodness of the estimation is dependent on the sample size. The bigger the sample size, the more accurate the estimation.</p></li>
<li><p>With the same size, the goodness of estimation is dependent on the population distribution.</p></li>
</ol>
</div>
<div id="why-bootstrap-procedure-works" class="section level3 hasAnchor" number="8.1.5">
<h3><span class="header-section-number">8.1.5</span> Why Bootstrap Procedure Works?<a href="bootstrapping-mlr-model.html#why-bootstrap-procedure-works" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a given population, if the sample size is large enough so that the empirical distribution is close to the theoretical distribution, we can take bootstrap samples for non-parametric inference. The following chart explains how bootstrap method works.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-96"></span>
<img src="img05/w05-HowBootstrapWorks.png" alt="How bootstrap procedure works." width="60%" />
<p class="caption">
Figure 8.3: How bootstrap procedure works.
</p>
</div>
<p>The above</p>
</div>
<div id="a-bigger-picture" class="section level3 hasAnchor" number="8.1.6">
<h3><span class="header-section-number">8.1.6</span> A Bigger Picture<a href="bootstrapping-mlr-model.html#a-bigger-picture" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-97"></span>
<img src="img05/w05-Bootstrap-Monte-Carlo.png" alt="Monte Carlo, Bootstrap, parametric, and asymptoic confidence intervals" width="100%" />
<p class="caption">
Figure 8.4: Monte Carlo, Bootstrap, parametric, and asymptoic confidence intervals
</p>
</div>
<p><br />
</p>
</div>
</div>
<div id="other-resampling-methods" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Other Resampling Methods<a href="bootstrapping-mlr-model.html#other-resampling-methods" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the last module, we listed several goodness-of-fit measures. The <strong>predicted residual error sum of squares (PRESS)</strong> is one of them. It definition is not clearly given. Before we discuss this measure in little bit more details, we first introduce a popular resampling method - Jackknife.</p>
<div id="jackknif-resampling" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Jackknif Resampling<a href="bootstrapping-mlr-model.html#jackknif-resampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The jackknife estimator of a parameter is found by systematically <strong>leaving out each observation from a dataset</strong> and <strong>calculating the parameter estimate over the remaining observations</strong> and <strong>then aggregating these calculations</strong>. It was developed by Maurice Quenouille in 1949 and refined in 1956. John Tukey expanded on the technique in 1958 and name the method “jackknife” because it is handy like a physical jack-knife. Jackknife resampling can improvise a solution for many specific problems more efficiently than some purpose-designed tools.</p>
<p>The basic leave-one-out Jackknife resampling method is illustrated in the following chart.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-98"></span>
<img src="img05/w05-JackknifeResampling.png" alt="Illustration of leave-one-out Jackknife resampling method" width="50%" />
<p class="caption">
Figure 8.5: Illustration of leave-one-out Jackknife resampling method
</p>
</div>
</div>
<div id="jackknife-for-predictive-sum-of-squares-press" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Jackknife for Predictive Sum of Squares (PRESS)<a href="bootstrapping-mlr-model.html#jackknife-for-predictive-sum-of-squares-press" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A fitted model having been produced, each observation in turn is removed and the model is refitted using the remaining observations. The out-of-sample predicted value is calculated for the omitted observation in each case, and the PRESS statistic is calculated as the sum of the squares of all the resulting prediction errors.</p>
<p><span class="math display">\[
\text{PRESS}=\sum _{{i=1}}^{n}(y_{i}-{\hat  {y}}_{{i,-i}})^{2}
\]</span></p>
<p>The PRESS statistic can be calculated for a number of candidate models for the same dataset, with the lowest values of PRESS indicating the best model.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="bootstrapping-mlr-model.html#cb109-1" tabindex="-1"></a>realestate <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/pengdsci/sta321/main/ww03/w03-Realestate.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb109-2"><a href="bootstrapping-mlr-model.html#cb109-2" tabindex="-1"></a>unitPrice <span class="ot">&lt;-</span> realestate<span class="sc">$</span>PriceUnitArea</span>
<span id="cb109-3"><a href="bootstrapping-mlr-model.html#cb109-3" tabindex="-1"></a>HouseAge <span class="ot">&lt;-</span> realestate<span class="sc">$</span>HouseAge</span>
<span id="cb109-4"><a href="bootstrapping-mlr-model.html#cb109-4" tabindex="-1"></a>nn <span class="ot">&lt;-</span> <span class="fu">length</span>(HouseAge)</span>
<span id="cb109-5"><a href="bootstrapping-mlr-model.html#cb109-5" tabindex="-1"></a>JK.pred <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb109-6"><a href="bootstrapping-mlr-model.html#cb109-6" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nn){</span>
<span id="cb109-7"><a href="bootstrapping-mlr-model.html#cb109-7" tabindex="-1"></a>  unitPrice0 <span class="ot">&lt;-</span> unitPrice[<span class="sc">-</span>i]</span>
<span id="cb109-8"><a href="bootstrapping-mlr-model.html#cb109-8" tabindex="-1"></a>  HouseAge0 <span class="ot">&lt;-</span> HouseAge[<span class="sc">-</span>i]</span>
<span id="cb109-9"><a href="bootstrapping-mlr-model.html#cb109-9" tabindex="-1"></a>  mm <span class="ot">&lt;-</span> <span class="fu">lm</span>(unitPrice0 <span class="sc">~</span> HouseAge0)</span>
<span id="cb109-10"><a href="bootstrapping-mlr-model.html#cb109-10" tabindex="-1"></a>  JK.pred[i] <span class="ot">=</span> <span class="fu">as.vector</span>(<span class="fu">predict</span>(mm, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">HouseAge0 =</span> HouseAge[i])))</span>
<span id="cb109-11"><a href="bootstrapping-mlr-model.html#cb109-11" tabindex="-1"></a>}</span>
<span id="cb109-12"><a href="bootstrapping-mlr-model.html#cb109-12" tabindex="-1"></a>PRESS <span class="ot">=</span> <span class="fu">sum</span>((unitPrice<span class="sc">-</span>JK.pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb109-13"><a href="bootstrapping-mlr-model.html#cb109-13" tabindex="-1"></a>PRESS</span></code></pre></div>
<pre><code>## [1] 73815.25</code></pre>
</div>
<div id="some-comments-on-jackknife" class="section level3 hasAnchor" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> Some Comments on Jackknife<a href="bootstrapping-mlr-model.html#some-comments-on-jackknife" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Jackknife samples can also be used for estimating population parameters just like what we did in bootstrap methods, but the procedure is not as straightforward as that of bootstrap. We will not go to details in this direction.</p></li>
<li><p>The logic of Jackknife sampling is used to define various data-driven methods that used in modern statistics, data science and machine learning. One of such methods is <strong>cross-validation</strong>. We will introduce this method in the second part this course - generalized linear regression.</p></li>
</ul>
<p>/</p>
</div>
</div>
<div id="parametric-linear-regression-model" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Parametric Linear Regression Model<a href="bootstrapping-mlr-model.html#parametric-linear-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For reference, we copy the code from the last note that creates the analytic data set for the final model and the summarized statistics of the model as well.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="bootstrapping-mlr-model.html#cb111-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb111-2"><a href="bootstrapping-mlr-model.html#cb111-2" tabindex="-1"></a>housingURL <span class="ot">=</span> <span class="st">&quot;https://raw.githubusercontent.com/pengdsci/sta321/main/ww03/w03-Realestate.csv&quot;</span></span>
<span id="cb111-3"><a href="bootstrapping-mlr-model.html#cb111-3" tabindex="-1"></a>realestate0 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(housingURL , <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb111-4"><a href="bootstrapping-mlr-model.html#cb111-4" tabindex="-1"></a>realestate <span class="ot">&lt;-</span> realestate0[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb111-5"><a href="bootstrapping-mlr-model.html#cb111-5" tabindex="-1"></a><span class="co"># longitude and latitude will be used to make a map in the upcoming analysis.</span></span>
<span id="cb111-6"><a href="bootstrapping-mlr-model.html#cb111-6" tabindex="-1"></a>lat <span class="ot">&lt;-</span> realestate<span class="sc">$</span>Latitude</span>
<span id="cb111-7"><a href="bootstrapping-mlr-model.html#cb111-7" tabindex="-1"></a>lon <span class="ot">&lt;-</span> realestate<span class="sc">$</span>Longitude</span>
<span id="cb111-8"><a href="bootstrapping-mlr-model.html#cb111-8" tabindex="-1"></a><span class="do">## define the geo.group variable</span></span>
<span id="cb111-9"><a href="bootstrapping-mlr-model.html#cb111-9" tabindex="-1"></a><span class="do">## top-right region = TRUE, other region = FALSE</span></span>
<span id="cb111-10"><a href="bootstrapping-mlr-model.html#cb111-10" tabindex="-1"></a>geo.group <span class="ot">&lt;-</span> (lon <span class="sc">&gt;</span> <span class="fl">121.529</span>) <span class="sc">&amp;</span> (lat <span class="sc">&gt;</span> <span class="fl">24.96</span>)     </span>
<span id="cb111-11"><a href="bootstrapping-mlr-model.html#cb111-11" tabindex="-1"></a><span class="co"># convert the logical values to character values.</span></span>
<span id="cb111-12"><a href="bootstrapping-mlr-model.html#cb111-12" tabindex="-1"></a>realestate<span class="sc">$</span>geo.group <span class="ot">&lt;-</span> <span class="fu">as.character</span>(geo.group)  </span>
<span id="cb111-13"><a href="bootstrapping-mlr-model.html#cb111-13" tabindex="-1"></a><span class="co"># convert transaction year to dummy.</span></span>
<span id="cb111-14"><a href="bootstrapping-mlr-model.html#cb111-14" tabindex="-1"></a>realestate<span class="sc">$</span>sale.year <span class="ot">&lt;-</span> <span class="fu">as.character</span>(realestate<span class="sc">$</span>TransactionYear) </span>
<span id="cb111-15"><a href="bootstrapping-mlr-model.html#cb111-15" tabindex="-1"></a><span class="co"># re-scale distance: foot -&gt; kilo feet</span></span>
<span id="cb111-16"><a href="bootstrapping-mlr-model.html#cb111-16" tabindex="-1"></a>realestate<span class="sc">$</span>Dist2MRT.kilo <span class="ot">&lt;-</span> (realestate<span class="sc">$</span>Distance2MRT)<span class="sc">/</span><span class="dv">1000</span> </span>
<span id="cb111-17"><a href="bootstrapping-mlr-model.html#cb111-17" tabindex="-1"></a><span class="co"># keep only variables to be used in the candidate models</span></span>
<span id="cb111-18"><a href="bootstrapping-mlr-model.html#cb111-18" tabindex="-1"></a>final.data <span class="ot">=</span> realestate[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>)]          </span>
<span id="cb111-19"><a href="bootstrapping-mlr-model.html#cb111-19" tabindex="-1"></a>final.data<span class="sc">$</span>logAreaPrice <span class="ot">=</span> <span class="fu">log</span>(final.data<span class="sc">$</span>PriceUnitArea)  <span class="co"># </span></span>
<span id="cb111-20"><a href="bootstrapping-mlr-model.html#cb111-20" tabindex="-1"></a><span class="do">## the final model</span></span>
<span id="cb111-21"><a href="bootstrapping-mlr-model.html#cb111-21" tabindex="-1"></a>log.price <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(PriceUnitArea) <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb111-22"><a href="bootstrapping-mlr-model.html#cb111-22" tabindex="-1"></a>                 Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data)</span>
<span id="cb111-23"><a href="bootstrapping-mlr-model.html#cb111-23" tabindex="-1"></a>log.price02 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logAreaPrice <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb111-24"><a href="bootstrapping-mlr-model.html#cb111-24" tabindex="-1"></a>                 Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data)</span>
<span id="cb111-25"><a href="bootstrapping-mlr-model.html#cb111-25" tabindex="-1"></a>cmtrx <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(log.price)<span class="sc">$</span>coef,<span class="dv">4</span>)</span>
<span id="cb111-26"><a href="bootstrapping-mlr-model.html#cb111-26" tabindex="-1"></a>cmtrx02 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">summary</span>(log.price02)<span class="sc">$</span>coef)</span>
<span id="cb111-27"><a href="bootstrapping-mlr-model.html#cb111-27" tabindex="-1"></a><span class="fu">kable</span>(cmtrx, <span class="at">caption =</span> <span class="st">&quot;Inferential Statistics of Final Model&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-100">Table 8.1: </span>Inferential Statistics of Final Model</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">3.5724</td>
<td align="right">0.0443</td>
<td align="right">80.5990</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">HouseAge</td>
<td align="right">-0.0076</td>
<td align="right">0.0010</td>
<td align="right">-7.4985</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">NumConvenStores</td>
<td align="right">0.0275</td>
<td align="right">0.0049</td>
<td align="right">5.5987</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">sale.year2013</td>
<td align="right">0.0806</td>
<td align="right">0.0244</td>
<td align="right">3.2963</td>
<td align="right">0.0011</td>
</tr>
<tr class="odd">
<td align="left">Dist2MRT.kilo</td>
<td align="right">-0.1445</td>
<td align="right">0.0138</td>
<td align="right">-10.5068</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">geo.groupTRUE</td>
<td align="right">0.1826</td>
<td align="right">0.0347</td>
<td align="right">5.2596</td>
<td align="right">0.0000</td>
</tr>
</tbody>
</table>
<p>The explicit expression of the final model is given by</p>
<p><span class="math display">\[
\log(price) =3.5723 - 0.0076\times HouseAge +0.0275\times NumConvenStores +
\]</span>
<span class="math display">\[   
0.0805\times Sale.year2013 - 0.1445\times Dist2MRT.kilo + 0.1826\times geo.groupTRUE
\]</span></p>
<p>As another example of the interpretation of the regression coefficient, we choose the coefficient associated with <strong>geo.group</strong>. In the output, you see the name of the dummy variable with the suffix <code>TRUE</code>, <strong>geo.groupTRUE</strong>. The suffix <strong>TRUE</strong> indicates that the dummy variable represents the category ‘TRUE’ of the category variable <strong>geo.group</strong>. The associated coefficient reflects the <strong>mean</strong> difference between the category <code>TRUE</code> and the baseline category <code>FALSE</code>. In R, the default baseline category is the lowest value of the categorical variable (in alphabetical order).</p>
<p>Let’s consider <strong>the set of all houses</strong> that are in the same conditions except the regions (region <code>TRUE</code> and region <code>FALSE</code> ) and the sale prices.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-101"></span>
<img src="img05/w05-map.jpg" alt="Location of Houses for Sale" width="80%" />
<p class="caption">
Figure 8.6: Location of Houses for Sale
</p>
</div>
<p><br />
</p>
</div>
<div id="bootstrap-cases-boot.c" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Bootstrap Cases (BOOT.C)<a href="bootstrapping-mlr-model.html#bootstrap-cases-boot.c" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we use bootstrapping cases to find the confidence intervals for the coefficients in the final regression model. The method was used in bootstrap simple linear regression (SLR) in week #3. The following code finds the confidence interval.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="bootstrapping-mlr-model.html#cb112-1" tabindex="-1"></a>log.price <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(PriceUnitArea) <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb112-2"><a href="bootstrapping-mlr-model.html#cb112-2" tabindex="-1"></a>                 Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data)</span>
<span id="cb112-3"><a href="bootstrapping-mlr-model.html#cb112-3" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb112-4"><a href="bootstrapping-mlr-model.html#cb112-4" tabindex="-1"></a>B <span class="ot">=</span> <span class="dv">1000</span>    <span class="co"># choose the number of bootstrap replicates.</span></span>
<span id="cb112-5"><a href="bootstrapping-mlr-model.html#cb112-5" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb112-6"><a href="bootstrapping-mlr-model.html#cb112-6" tabindex="-1"></a>num.p <span class="ot">=</span> <span class="fu">dim</span>(<span class="fu">model.frame</span>(log.price))[<span class="dv">2</span>]  <span class="co"># returns number of parameters </span></span>
<span id="cb112-7"><a href="bootstrapping-mlr-model.html#cb112-7" tabindex="-1"></a>smpl.n <span class="ot">=</span> <span class="fu">dim</span>(<span class="fu">model.frame</span>(log.price))[<span class="dv">1</span>] <span class="co"># sample size</span></span>
<span id="cb112-8"><a href="bootstrapping-mlr-model.html#cb112-8" tabindex="-1"></a><span class="do">## zero matrix to store bootstrap coefficients </span></span>
<span id="cb112-9"><a href="bootstrapping-mlr-model.html#cb112-9" tabindex="-1"></a>coef.mtrx <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>, B<span class="sc">*</span>num.p), <span class="at">ncol =</span> num.p)       </span>
<span id="cb112-10"><a href="bootstrapping-mlr-model.html#cb112-10" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb112-11"><a href="bootstrapping-mlr-model.html#cb112-11" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B){</span>
<span id="cb112-12"><a href="bootstrapping-mlr-model.html#cb112-12" tabindex="-1"></a>  bootc.id <span class="ot">=</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>smpl.n, smpl.n, <span class="at">replace =</span> <span class="cn">TRUE</span>) </span>
<span id="cb112-13"><a href="bootstrapping-mlr-model.html#cb112-13" tabindex="-1"></a>  <span class="co"># fit final model to the bootstrap sample</span></span>
<span id="cb112-14"><a href="bootstrapping-mlr-model.html#cb112-14" tabindex="-1"></a>  log.price.btc <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(PriceUnitArea) <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb112-15"><a href="bootstrapping-mlr-model.html#cb112-15" tabindex="-1"></a>                       Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data[bootc.id,])  </span>
<span id="cb112-16"><a href="bootstrapping-mlr-model.html#cb112-16" tabindex="-1"></a>  <span class="co"># extract coefs from bootstrap regression model  </span></span>
<span id="cb112-17"><a href="bootstrapping-mlr-model.html#cb112-17" tabindex="-1"></a>  coef.mtrx[i,] <span class="ot">=</span> <span class="fu">coef</span>(log.price.btc)      </span>
<span id="cb112-18"><a href="bootstrapping-mlr-model.html#cb112-18" tabindex="-1"></a>}</span></code></pre></div>
<p>We define an R function to make histograms of the bootstrap regression coefficients in the following. I will also use this function to make histograms for the residual bootstrap estimated regression coefficients as well.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="bootstrapping-mlr-model.html#cb113-1" tabindex="-1"></a>boot.hist <span class="ot">=</span> <span class="cf">function</span>(cmtrx, bt.coef.mtrx, var.id, var.nm){</span>
<span id="cb113-2"><a href="bootstrapping-mlr-model.html#cb113-2" tabindex="-1"></a>  <span class="do">## bt.coef.mtrx = matrix for storing bootstrap estimates of coefficients</span></span>
<span id="cb113-3"><a href="bootstrapping-mlr-model.html#cb113-3" tabindex="-1"></a>  <span class="do">## var.id = variable ID (1, 2, ..., k+1)</span></span>
<span id="cb113-4"><a href="bootstrapping-mlr-model.html#cb113-4" tabindex="-1"></a>  <span class="do">## var.nm = variable name on the hist title, </span></span>
<span id="cb113-5"><a href="bootstrapping-mlr-model.html#cb113-5" tabindex="-1"></a>  <span class="do">## must be the string in the double quotes</span></span>
<span id="cb113-6"><a href="bootstrapping-mlr-model.html#cb113-6" tabindex="-1"></a>  <span class="do">## coefficient matrix of the final model</span></span>
<span id="cb113-7"><a href="bootstrapping-mlr-model.html#cb113-7" tabindex="-1"></a>  <span class="do">## Bootstrap sampling distribution of the estimated coefficients</span></span>
<span id="cb113-8"><a href="bootstrapping-mlr-model.html#cb113-8" tabindex="-1"></a>  x1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(bt.coef.mtrx[,var.id]), <span class="fu">max</span>(bt.coef.mtrx[,var.id]), <span class="at">length=</span><span class="dv">300</span> )</span>
<span id="cb113-9"><a href="bootstrapping-mlr-model.html#cb113-9" tabindex="-1"></a>  y1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x1<span class="fl">.1</span>, <span class="fu">mean</span>(bt.coef.mtrx[,var.id]), <span class="fu">sd</span>(bt.coef.mtrx[,var.id]))</span>
<span id="cb113-10"><a href="bootstrapping-mlr-model.html#cb113-10" tabindex="-1"></a>  <span class="co"># height of the histogram - use it to make a nice-looking histogram.</span></span>
<span id="cb113-11"><a href="bootstrapping-mlr-model.html#cb113-11" tabindex="-1"></a>  highestbar <span class="ot">=</span> <span class="fu">max</span>(<span class="fu">hist</span>(bt.coef.mtrx[,var.id], <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>density) </span>
<span id="cb113-12"><a href="bootstrapping-mlr-model.html#cb113-12" tabindex="-1"></a>  ylimit <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">c</span>(y1<span class="fl">.1</span>,highestbar))</span>
<span id="cb113-13"><a href="bootstrapping-mlr-model.html#cb113-13" tabindex="-1"></a>  <span class="fu">hist</span>(bt.coef.mtrx[,var.id], <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> var.nm, <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, </span>
<span id="cb113-14"><a href="bootstrapping-mlr-model.html#cb113-14" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;azure1&quot;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,ylimit), <span class="at">border=</span><span class="st">&quot;lightseagreen&quot;</span>)</span>
<span id="cb113-15"><a href="bootstrapping-mlr-model.html#cb113-15" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="at">x =</span> x1<span class="fl">.1</span>, <span class="at">y =</span> y1<span class="fl">.1</span>, <span class="at">col =</span> <span class="st">&quot;red3&quot;</span>)</span>
<span id="cb113-16"><a href="bootstrapping-mlr-model.html#cb113-16" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">density</span>(bt.coef.mtrx[,var.id], <span class="at">adjust=</span><span class="dv">2</span>), <span class="at">col=</span><span class="st">&quot;blue&quot;</span>) </span>
<span id="cb113-17"><a href="bootstrapping-mlr-model.html#cb113-17" tabindex="-1"></a>  <span class="co">#legend(&quot;topright&quot;, c(&quot;&quot;))</span></span>
<span id="cb113-18"><a href="bootstrapping-mlr-model.html#cb113-18" tabindex="-1"></a>}</span></code></pre></div>
<p>The following histograms of the bootstrap estimates of regression coefficients represent the sampling distributions of the corresponding estimates in the final model.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="bootstrapping-mlr-model.html#cb114-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))  <span class="co"># histograms of bootstrap coefs</span></span>
<span id="cb114-2"><a href="bootstrapping-mlr-model.html#cb114-2" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">1</span>, <span class="at">var.nm =</span><span class="st">&quot;Intercept&quot;</span> )</span>
<span id="cb114-3"><a href="bootstrapping-mlr-model.html#cb114-3" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">2</span>, <span class="at">var.nm =</span><span class="st">&quot;House Age&quot;</span> )</span>
<span id="cb114-4"><a href="bootstrapping-mlr-model.html#cb114-4" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">3</span>, <span class="at">var.nm =</span><span class="st">&quot;Num Conven Stores&quot;</span> )</span>
<span id="cb114-5"><a href="bootstrapping-mlr-model.html#cb114-5" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">4</span>, <span class="at">var.nm =</span><span class="st">&quot;Year Sold&quot;</span> )</span>
<span id="cb114-6"><a href="bootstrapping-mlr-model.html#cb114-6" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">5</span>, <span class="at">var.nm =</span><span class="st">&quot;Dist to MRT&quot;</span> )</span>
<span id="cb114-7"><a href="bootstrapping-mlr-model.html#cb114-7" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>coef.mtrx, <span class="at">var.id=</span><span class="dv">6</span>, <span class="at">var.nm =</span><span class="st">&quot;Region&quot;</span> )</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-104"></span>
<img src="STA321EB_files/figure-html/unnamed-chunk-104-1.png" alt="(Case) Bootstrap confidence intervals of regression coefficients" width="672" />
<p class="caption">
Figure 8.7: (Case) Bootstrap confidence intervals of regression coefficients
</p>
</div>
<p>Two normal-density curves were placed on each of the histograms.</p>
<ul>
<li><p>The red <strong>density curve</strong> uses the estimated regression coefficients and their corresponding standard error in the output of the regression procedure. The p-values reported in the output are based on the red curve.</p></li>
<li><p>The <strong>blue curve</strong> is a non-parametric data-driven estimate of the density of bootstrap sampling distribution. The bootstrap confidence intervals of the regressions are based on these non-parametric bootstrap sampling distributions.</p></li>
</ul>
<p>We can see from the above histograms that the two density curves in all histograms are close to each other. we would expect that significance test results and the corresponding bootstrap confidence intervals are consistent. Next, we find 95% bootstrap confidence intervals of each regression coefficient and combined them with the output of the final model.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="bootstrapping-mlr-model.html#cb115-1" tabindex="-1"></a>num.p <span class="ot">=</span> <span class="fu">dim</span>(coef.mtrx)[<span class="dv">2</span>]  <span class="co"># number of parameters</span></span>
<span id="cb115-2"><a href="bootstrapping-mlr-model.html#cb115-2" tabindex="-1"></a>btc.ci <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb115-3"><a href="bootstrapping-mlr-model.html#cb115-3" tabindex="-1"></a>btc.wd <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb115-4"><a href="bootstrapping-mlr-model.html#cb115-4" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num.p){</span>
<span id="cb115-5"><a href="bootstrapping-mlr-model.html#cb115-5" tabindex="-1"></a>  lci<span class="fl">.025</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">quantile</span>(coef.mtrx[, i], <span class="fl">0.025</span>, <span class="at">type =</span> <span class="dv">2</span>),<span class="dv">8</span>)</span>
<span id="cb115-6"><a href="bootstrapping-mlr-model.html#cb115-6" tabindex="-1"></a>  uci<span class="fl">.975</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">quantile</span>(coef.mtrx[, i],<span class="fl">0.975</span>, <span class="at">type =</span> <span class="dv">2</span> ),<span class="dv">8</span>)</span>
<span id="cb115-7"><a href="bootstrapping-mlr-model.html#cb115-7" tabindex="-1"></a>  btc.wd[i] <span class="ot">=</span>  uci<span class="fl">.975</span> <span class="sc">-</span> lci<span class="fl">.025</span></span>
<span id="cb115-8"><a href="bootstrapping-mlr-model.html#cb115-8" tabindex="-1"></a>  btc.ci[i] <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">&quot;     [&quot;</span>, <span class="fu">round</span>(lci<span class="fl">.025</span>,<span class="dv">4</span>),<span class="st">&quot;, &quot;</span>, <span class="fu">round</span>(uci<span class="fl">.975</span>,<span class="dv">4</span>),<span class="st">&quot;]&quot;</span>)</span>
<span id="cb115-9"><a href="bootstrapping-mlr-model.html#cb115-9" tabindex="-1"></a> }</span>
<span id="cb115-10"><a href="bootstrapping-mlr-model.html#cb115-10" tabindex="-1"></a><span class="co">#btci.95 = as.data.frame(btc.ci)</span></span>
<span id="cb115-11"><a href="bootstrapping-mlr-model.html#cb115-11" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">cbind</span>(cmtrx, btc.ci), </span>
<span id="cb115-12"><a href="bootstrapping-mlr-model.html#cb115-12" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">&quot;Regression Coefficient Matrix&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-105">Table 8.2: </span>Regression Coefficient Matrix</caption>
<colgroup>
<col width="18%" />
<col width="10%" />
<col width="12%" />
<col width="10%" />
<col width="21%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Estimate</th>
<th align="left">Std. Error</th>
<th align="left">t value</th>
<th align="left">Pr(&gt;|t|)</th>
<th align="left">btc.ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="left">3.5724</td>
<td align="left">0.0443</td>
<td align="left">80.599</td>
<td align="left">0</td>
<td align="left">[ 3.4743 , 3.6596 ]</td>
</tr>
<tr class="even">
<td align="left">HouseAge</td>
<td align="left">-0.0076</td>
<td align="left">0.001</td>
<td align="left">-7.4985</td>
<td align="left">0</td>
<td align="left">[ -0.0097 , -0.0057 ]</td>
</tr>
<tr class="odd">
<td align="left">NumConvenStores</td>
<td align="left">0.0275</td>
<td align="left">0.0049</td>
<td align="left">5.5987</td>
<td align="left">0</td>
<td align="left">[ 0.0166 , 0.0376 ]</td>
</tr>
<tr class="even">
<td align="left">sale.year2013</td>
<td align="left">0.0806</td>
<td align="left">0.0244</td>
<td align="left">3.2963</td>
<td align="left">0.0011</td>
<td align="left">[ 0.0379 , 0.1228 ]</td>
</tr>
<tr class="odd">
<td align="left">Dist2MRT.kilo</td>
<td align="left">-0.1445</td>
<td align="left">0.0138</td>
<td align="left">-10.5068</td>
<td align="left">0</td>
<td align="left">[ -0.1712 , -0.1153 ]</td>
</tr>
<tr class="even">
<td align="left">geo.groupTRUE</td>
<td align="left">0.1826</td>
<td align="left">0.0347</td>
<td align="left">5.2596</td>
<td align="left">0</td>
<td align="left">[ 0.1116 , 0.2614 ]</td>
</tr>
</tbody>
</table>
<p>We can see from the above table of summarized statistics, the significance tests of regression coefficients based on the p-values and the corresponding 95% confidence intervals are consistent.</p>
</div>
<div id="bootstrap-residuals-boot.r" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Bootstrap Residuals (BOOT.R)<a href="bootstrapping-mlr-model.html#bootstrap-residuals-boot.r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we introduce bootstrap residual methods to construct bootstrap confidence intervals. The idea is straightforward and is summarized in the following.</p>
<p><img src="img05/w05-BootsResiduals.png" width="100%" style="display: block; margin: auto;" /></p>
<div id="fitted-model" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> Fitted Model<a href="bootstrapping-mlr-model.html#fitted-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Assume that the fitted regression model is given by</p>
<p><span class="math display">\[
\begin{array}{ccc}
y_1 &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{11} + \hat{\beta}_2 x_{12} + \cdots + \hat{\beta}_k x_{1k} + e_1  \\
y_2 &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{21} + \hat{\beta}_2 x_{22} + \cdots + \hat{\beta}_k x_{2k} + e_2  \\
y_3 &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{31} + \hat{\beta}_2 x_{32} + \cdots + \hat{\beta}_k x_{3k} + e_3  \\
\vdots &amp; \vdots &amp; \vdots \\
y_n &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{n1} + \hat{\beta}_2 x_{n2} + \cdots + \hat{\beta}_k x_{nk} + e_n
\end{array}
\]</span></p>
<p>where <span class="math inline">\(\{e_1, e_2, \cdots, e_n \}\)</span> is the set of residuals obtained from the final model. <span class="math inline">\(\{x_{i1}, x_{i2}, \cdots, x_{ik} \}\)</span> is the i-th record from the data, and <span class="math inline">\(\{ \hat{\beta}_0, \hat{\beta}_1, \cdots, \hat{\beta}_k \}\)</span></p>
<p>The distribution of the residuals is depicted in the following histogram.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="bootstrapping-mlr-model.html#cb116-1" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">sort</span>(log.price<span class="sc">$</span>residuals),<span class="at">n=</span><span class="dv">40</span>,</span>
<span id="cb116-2"><a href="bootstrapping-mlr-model.html#cb116-2" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Residuals&quot;</span>,</span>
<span id="cb116-3"><a href="bootstrapping-mlr-model.html#cb116-3" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;lightblue&quot;</span>,</span>
<span id="cb116-4"><a href="bootstrapping-mlr-model.html#cb116-4" tabindex="-1"></a>     <span class="at">border=</span><span class="st">&quot;navy&quot;</span>,</span>
<span id="cb116-5"><a href="bootstrapping-mlr-model.html#cb116-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histogram of Residuals&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-107"></span>
<img src="STA321EB_files/figure-html/unnamed-chunk-107-1.png" alt="Distribution of residuals of the linear regression model" width="672" />
<p class="caption">
Figure 8.8: Distribution of residuals of the linear regression model
</p>
</div>
<p>The above histogram reveals the same information as we saw in the residual plot in the last note: (1) one out-lier; (2). The distribution is skewed to the right.</p>
</div>
<div id="residual-bootstrap-samples" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Residual Bootstrap Samples<a href="bootstrapping-mlr-model.html#residual-bootstrap-samples" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The residual bootstrap sample of <span class="math inline">\(y\)</span> is defined in the following:</p>
<ul>
<li><p>Take a <strong>bootstrap sample</strong> from the set of residuals <span class="math inline">\(\{e_1, e_2, \cdots, e_n \}\)</span>, denoted by <span class="math inline">\(\{e_1^{*}, e_2^{*}, \cdots, e_n^{*} \}\)</span>.</p></li>
<li><p>The residual bootstrap sample of <span class="math inline">\(\{y_1^{*}, y_2^{*}, \cdots, y_n^{*} \}\)</span> is defined by</p></li>
</ul>
<p><span class="math display">\[
\begin{array}{ccc}
y_1^{*} &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{11} + \hat{\beta}_2 x_{12} + \cdots + \hat{\beta}_k x_{1k} + e_1^{*}  \\
y_2^{*} &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{21} + \hat{\beta}_2 x_{22} + \cdots + \hat{\beta}_k x_{2k} + e_2^{*}  \\
y_3^{*} &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{31} + \hat{\beta}_2 x_{32} + \cdots + \hat{\beta}_k x_{3k} + e_3^{*}  \\
\vdots &amp; \vdots &amp; \vdots \\
y_n^{*} &amp; = &amp;  \hat{\beta}_0 + \hat{\beta}_1 x_{n1} + \hat{\beta}_2 x_{n2} + \cdots + \hat{\beta}_k x_{nk} + e_n^{*}
\end{array}
\]</span></p>
<p>The above definition implies that the residual bootstrap is equal to the <strong>fitted value + bootstrap residuals</strong>.</p>
<ul>
<li>The resulting <strong>residual bootstrap sample</strong> is given by</li>
</ul>
<p><span class="math display">\[
\begin{array}{cccccc}
y_1^{*} &amp;  x_{11} &amp;  x_{12} &amp; \cdots &amp; x_{1k}  \\
y_2^{*} &amp;  x_{21} &amp;  x_{22} &amp; \cdots &amp; x_{2k}  \\
y_3^{*} &amp;  x_{31} &amp;  x_{32} &amp; \cdots &amp; x_{3k}  \\
\vdots  &amp;  \vdots &amp;  \vdots &amp; \vdots &amp; \vdots  \\
y_n^{*} &amp;  x_{n1} &amp;  x_{n2} &amp; \cdots &amp; x_{nk}
\end{array}
\]</span></p>
<ul>
<li>We fit the final model to the <strong>residual bootstrap sample</strong> and denote the bootstrap estimates of regression coefficients in the following</li>
</ul>
<p><span class="math display">\[
\{ \hat{\beta}_0^{*}, \hat{\beta}_1^{*},  \cdots, \hat{\beta}_k^{*} \}
\]</span></p>
<ul>
<li>Repeat the above steps B times, we obtain the following bootstrap estimates</li>
</ul>
<p><span class="math display">\[
\begin{array}{cccccc}
\hat{\beta}_0^{1*} &amp; \hat{\beta}_1^{1*} &amp;  \cdots  &amp; \hat{\beta}_k^{1*}  \\
\hat{\beta}_0^{2*} &amp; \hat{\beta}_1^{2*} &amp;  \cdots  &amp; \hat{\beta}_k^{2*}  \\
\hat{\beta}_0^{3*} &amp; \hat{\beta}_1^{3*} &amp;  \cdots  &amp; \hat{\beta}_k^{3*}  \\
\vdots  &amp;  \vdots &amp;  \vdots &amp; \vdots  \\
\hat{\beta}_0^{b*} &amp; \hat{\beta}_1^{b*} &amp;  \cdots  &amp; \hat{\beta}_k^{b*}  \\
\vdots  &amp;  \vdots &amp;  \vdots &amp; \vdots  \\
\hat{\beta}_0^{B*} &amp; \hat{\beta}_1^{B*} &amp;  \cdots  &amp; \hat{\beta}_k^{B*}  \\
\end{array}
\]</span></p>
<p>The residual bootstrap confidence intervals of regression coefficients can be estimated from the above bootstrap coefficients.</p>
</div>
<div id="implementation-of-residual-bootstrap-regression" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> Implementation of Residual Bootstrap Regression<a href="bootstrapping-mlr-model.html#implementation-of-residual-bootstrap-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following code generates bootstrap confidence intervals of regression coefficients.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="bootstrapping-mlr-model.html#cb117-1" tabindex="-1"></a><span class="do">## Final model</span></span>
<span id="cb117-2"><a href="bootstrapping-mlr-model.html#cb117-2" tabindex="-1"></a>log.price <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(PriceUnitArea) <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb117-3"><a href="bootstrapping-mlr-model.html#cb117-3" tabindex="-1"></a>                 Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data)</span>
<span id="cb117-4"><a href="bootstrapping-mlr-model.html#cb117-4" tabindex="-1"></a>model.resid <span class="ot">=</span> log.price<span class="sc">$</span>residuals</span>
<span id="cb117-5"><a href="bootstrapping-mlr-model.html#cb117-5" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb117-6"><a href="bootstrapping-mlr-model.html#cb117-6" tabindex="-1"></a>B<span class="ot">=</span><span class="dv">1000</span></span>
<span id="cb117-7"><a href="bootstrapping-mlr-model.html#cb117-7" tabindex="-1"></a>num.p <span class="ot">=</span> <span class="fu">dim</span>(<span class="fu">model.matrix</span>(log.price))[<span class="dv">2</span>]   <span class="co"># number of parameters</span></span>
<span id="cb117-8"><a href="bootstrapping-mlr-model.html#cb117-8" tabindex="-1"></a>samp.n <span class="ot">=</span> <span class="fu">dim</span>(<span class="fu">model.matrix</span>(log.price))[<span class="dv">1</span>]  <span class="co"># sample size</span></span>
<span id="cb117-9"><a href="bootstrapping-mlr-model.html#cb117-9" tabindex="-1"></a>btr.mtrx <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">6</span><span class="sc">*</span>B), <span class="at">ncol=</span>num.p) <span class="co"># zero matrix to store boot coefs</span></span>
<span id="cb117-10"><a href="bootstrapping-mlr-model.html#cb117-10" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B){</span>
<span id="cb117-11"><a href="bootstrapping-mlr-model.html#cb117-11" tabindex="-1"></a>  <span class="do">## Bootstrap response values</span></span>
<span id="cb117-12"><a href="bootstrapping-mlr-model.html#cb117-12" tabindex="-1"></a>  bt.lg.price <span class="ot">=</span> log.price<span class="sc">$</span>fitted.values <span class="sc">+</span> </span>
<span id="cb117-13"><a href="bootstrapping-mlr-model.html#cb117-13" tabindex="-1"></a>        <span class="fu">sample</span>(log.price<span class="sc">$</span>residuals, samp.n, <span class="at">replace =</span> <span class="cn">TRUE</span>)  <span class="co"># bootstrap residuals</span></span>
<span id="cb117-14"><a href="bootstrapping-mlr-model.html#cb117-14" tabindex="-1"></a>  <span class="co"># replace PriceUnitArea with bootstrap log price</span></span>
<span id="cb117-15"><a href="bootstrapping-mlr-model.html#cb117-15" tabindex="-1"></a>  final.data<span class="sc">$</span>bt.lg.price <span class="ot">=</span>  bt.lg.price   <span class="co">#  send the boot response to the data</span></span>
<span id="cb117-16"><a href="bootstrapping-mlr-model.html#cb117-16" tabindex="-1"></a>  btr.model <span class="ot">=</span> <span class="fu">lm</span>(bt.lg.price <span class="sc">~</span> HouseAge <span class="sc">+</span> NumConvenStores <span class="sc">+</span> sale.year <span class="sc">+</span>  </span>
<span id="cb117-17"><a href="bootstrapping-mlr-model.html#cb117-17" tabindex="-1"></a>                 Dist2MRT.kilo  <span class="sc">+</span> geo.group, <span class="at">data =</span> final.data)   <span class="co"># b</span></span>
<span id="cb117-18"><a href="bootstrapping-mlr-model.html#cb117-18" tabindex="-1"></a>  btr.mtrx[i,]<span class="ot">=</span>btr.model<span class="sc">$</span>coefficients</span>
<span id="cb117-19"><a href="bootstrapping-mlr-model.html#cb117-19" tabindex="-1"></a>}</span></code></pre></div>
<p>Next, we make histograms of the residual bootstrap estimates of the regression coefficients.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="bootstrapping-mlr-model.html#cb118-1" tabindex="-1"></a>boot.hist <span class="ot">=</span> <span class="cf">function</span>(bt.coef.mtrx, var.id, var.nm){</span>
<span id="cb118-2"><a href="bootstrapping-mlr-model.html#cb118-2" tabindex="-1"></a>  <span class="do">## bt.coef.mtrx = matrix for storing bootstrap estimates of coefficients</span></span>
<span id="cb118-3"><a href="bootstrapping-mlr-model.html#cb118-3" tabindex="-1"></a>  <span class="do">## var.id = variable ID (1, 2, ..., k+1)</span></span>
<span id="cb118-4"><a href="bootstrapping-mlr-model.html#cb118-4" tabindex="-1"></a>  <span class="do">## var.nm = variable name on the hist title, </span></span>
<span id="cb118-5"><a href="bootstrapping-mlr-model.html#cb118-5" tabindex="-1"></a>  <span class="do">## must be the string in the double quotes</span></span>
<span id="cb118-6"><a href="bootstrapping-mlr-model.html#cb118-6" tabindex="-1"></a>  <span class="do">## Bootstrap sampling distribution of the estimated coefficients</span></span>
<span id="cb118-7"><a href="bootstrapping-mlr-model.html#cb118-7" tabindex="-1"></a>  x1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(bt.coef.mtrx[,var.id]), <span class="fu">max</span>(bt.coef.mtrx[,var.id]), <span class="at">length=</span><span class="dv">300</span> )</span>
<span id="cb118-8"><a href="bootstrapping-mlr-model.html#cb118-8" tabindex="-1"></a>  y1<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x1<span class="fl">.1</span>, <span class="fu">mean</span>(bt.coef.mtrx[,var.id]), <span class="fu">sd</span>(bt.coef.mtrx[,var.id]))</span>
<span id="cb118-9"><a href="bootstrapping-mlr-model.html#cb118-9" tabindex="-1"></a>  <span class="co"># height of the histogram - use it to make a nice-looking histogram.</span></span>
<span id="cb118-10"><a href="bootstrapping-mlr-model.html#cb118-10" tabindex="-1"></a>  highestbar <span class="ot">=</span> <span class="fu">max</span>(<span class="fu">hist</span>(bt.coef.mtrx[,var.id], <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>density) </span>
<span id="cb118-11"><a href="bootstrapping-mlr-model.html#cb118-11" tabindex="-1"></a>  ylimit <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">c</span>(y1<span class="fl">.1</span>,highestbar))</span>
<span id="cb118-12"><a href="bootstrapping-mlr-model.html#cb118-12" tabindex="-1"></a>  <span class="fu">hist</span>(bt.coef.mtrx[,var.id], <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> var.nm, <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, </span>
<span id="cb118-13"><a href="bootstrapping-mlr-model.html#cb118-13" tabindex="-1"></a>       <span class="at">col =</span> <span class="st">&quot;azure1&quot;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,ylimit), <span class="at">border=</span><span class="st">&quot;lightseagreen&quot;</span>)</span>
<span id="cb118-14"><a href="bootstrapping-mlr-model.html#cb118-14" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="at">x =</span> x1<span class="fl">.1</span>, <span class="at">y =</span> y1<span class="fl">.1</span>, <span class="at">col =</span> <span class="st">&quot;red3&quot;</span>)       <span class="co"># normal density curve         </span></span>
<span id="cb118-15"><a href="bootstrapping-mlr-model.html#cb118-15" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">density</span>(bt.coef.mtrx[,var.id], <span class="at">adjust=</span><span class="dv">2</span>), <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)    <span class="co"># loess curve</span></span>
<span id="cb118-16"><a href="bootstrapping-mlr-model.html#cb118-16" tabindex="-1"></a>} </span></code></pre></div>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="bootstrapping-mlr-model.html#cb119-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))  <span class="co"># histograms of bootstrap coefs</span></span>
<span id="cb119-2"><a href="bootstrapping-mlr-model.html#cb119-2" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">1</span>, <span class="at">var.nm =</span><span class="st">&quot;Intercept&quot;</span> )</span>
<span id="cb119-3"><a href="bootstrapping-mlr-model.html#cb119-3" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">2</span>, <span class="at">var.nm =</span><span class="st">&quot;House Age&quot;</span> )</span>
<span id="cb119-4"><a href="bootstrapping-mlr-model.html#cb119-4" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">3</span>, <span class="at">var.nm =</span><span class="st">&quot;Num Conven Stores&quot;</span> )</span>
<span id="cb119-5"><a href="bootstrapping-mlr-model.html#cb119-5" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">4</span>, <span class="at">var.nm =</span><span class="st">&quot;Year Sold&quot;</span> )</span>
<span id="cb119-6"><a href="bootstrapping-mlr-model.html#cb119-6" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">5</span>, <span class="at">var.nm =</span><span class="st">&quot;Dist to MRT&quot;</span> )</span>
<span id="cb119-7"><a href="bootstrapping-mlr-model.html#cb119-7" tabindex="-1"></a><span class="fu">boot.hist</span>(<span class="at">bt.coef.mtrx=</span>btr.mtrx, <span class="at">var.id=</span><span class="dv">6</span>, <span class="at">var.nm =</span><span class="st">&quot;Region&quot;</span> )</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-110"></span>
<img src="STA321EB_files/figure-html/unnamed-chunk-110-1.png" alt="(Residual) Bootstrap confidence intervals" width="672" />
<p class="caption">
Figure 8.9: (Residual) Bootstrap confidence intervals
</p>
</div>
<p>The residual bootstrap sampling distributions of each estimated regression coefficient. The normal and LOESS curves are close to each other. This also indicated that the inference of the significance of variables based on p-values and residual bootstrap will yield the same results.</p>
<p>The 95% residual bootstrap confidence intervals are given in the following</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="bootstrapping-mlr-model.html#cb120-1" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb120-2"><a href="bootstrapping-mlr-model.html#cb120-2" tabindex="-1"></a>num.p <span class="ot">=</span> <span class="fu">dim</span>(coef.mtrx)[<span class="dv">2</span>]  <span class="co"># number of parameters</span></span>
<span id="cb120-3"><a href="bootstrapping-mlr-model.html#cb120-3" tabindex="-1"></a>btr.ci <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb120-4"><a href="bootstrapping-mlr-model.html#cb120-4" tabindex="-1"></a>btr.wd <span class="ot">=</span> <span class="cn">NULL</span></span>
<span id="cb120-5"><a href="bootstrapping-mlr-model.html#cb120-5" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num.p){</span>
<span id="cb120-6"><a href="bootstrapping-mlr-model.html#cb120-6" tabindex="-1"></a>  lci<span class="fl">.025</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">quantile</span>(btr.mtrx[, i], <span class="fl">0.025</span>, <span class="at">type =</span> <span class="dv">2</span>),<span class="dv">8</span>)</span>
<span id="cb120-7"><a href="bootstrapping-mlr-model.html#cb120-7" tabindex="-1"></a>  uci<span class="fl">.975</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">quantile</span>(btr.mtrx[, i],<span class="fl">0.975</span>, <span class="at">type =</span> <span class="dv">2</span> ),<span class="dv">8</span>)</span>
<span id="cb120-8"><a href="bootstrapping-mlr-model.html#cb120-8" tabindex="-1"></a>  btr.wd[i] <span class="ot">=</span> uci<span class="fl">.975</span> <span class="sc">-</span> lci<span class="fl">.025</span></span>
<span id="cb120-9"><a href="bootstrapping-mlr-model.html#cb120-9" tabindex="-1"></a>  btr.ci[i] <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">&quot;[&quot;</span>, <span class="fu">round</span>(lci<span class="fl">.025</span>,<span class="dv">4</span>),<span class="st">&quot;, &quot;</span>, <span class="fu">round</span>(uci<span class="fl">.975</span>,<span class="dv">4</span>),<span class="st">&quot;]&quot;</span>)</span>
<span id="cb120-10"><a href="bootstrapping-mlr-model.html#cb120-10" tabindex="-1"></a>}</span>
<span id="cb120-11"><a href="bootstrapping-mlr-model.html#cb120-11" tabindex="-1"></a><span class="co">#as.data.frame(btc.ci)</span></span>
<span id="cb120-12"><a href="bootstrapping-mlr-model.html#cb120-12" tabindex="-1"></a><span class="fu">cbind</span>(cmtrx, <span class="at">btr.ci.95=</span>btr.ci)</span></code></pre></div>
<pre><code>##                 Estimate  Std. Error t value    Pr(&gt;|t|)
## (Intercept)     &quot;3.5724&quot;  &quot;0.0443&quot;   &quot;80.599&quot;   &quot;0&quot;     
## HouseAge        &quot;-0.0076&quot; &quot;0.001&quot;    &quot;-7.4985&quot;  &quot;0&quot;     
## NumConvenStores &quot;0.0275&quot;  &quot;0.0049&quot;   &quot;5.5987&quot;   &quot;0&quot;     
## sale.year2013   &quot;0.0806&quot;  &quot;0.0244&quot;   &quot;3.2963&quot;   &quot;0.0011&quot;
## Dist2MRT.kilo   &quot;-0.1445&quot; &quot;0.0138&quot;   &quot;-10.5068&quot; &quot;0&quot;     
## geo.groupTRUE   &quot;0.1826&quot;  &quot;0.0347&quot;   &quot;5.2596&quot;   &quot;0&quot;     
##                 btr.ci.95               
## (Intercept)     &quot;[ 3.4848 ,  3.6588 ]&quot;  
## HouseAge        &quot;[ -0.0096 ,  -0.0055 ]&quot;
## NumConvenStores &quot;[ 0.0185 ,  0.0373 ]&quot;  
## sale.year2013   &quot;[ 0.035 ,  0.1291 ]&quot;   
## Dist2MRT.kilo   &quot;[ -0.1721 ,  -0.119 ]&quot; 
## geo.groupTRUE   &quot;[ 0.1124 ,  0.2502 ]&quot;</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="bootstrapping-mlr-model.html#cb122-1" tabindex="-1"></a><span class="co">#kable(cbind(cmtrx, btr.ci.95=btr.ci), </span></span>
<span id="cb122-2"><a href="bootstrapping-mlr-model.html#cb122-2" tabindex="-1"></a><span class="co">#      caption = &quot;Regression Coefficient Matrix with 95% Residual Bootstrap CI&quot;)</span></span></code></pre></div>
<p>As expected, the residual bootstrap confidence intervals yield the same results as p-values do. This is because the sample size is large enough so that the sampling distributions of estimated coefficients have sufficiently good approximations of normal distributions.</p>
</div>
<div id="combining-all-inferential-statistics" class="section level3 hasAnchor" number="8.5.4">
<h3><span class="header-section-number">8.5.4</span> Combining All Inferential Statistics<a href="bootstrapping-mlr-model.html#combining-all-inferential-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Finally, we put all inferential statistics in a single table so we can compare these results.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="bootstrapping-mlr-model.html#cb123-1" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">cbind</span>(cmtrx[,<span class="sc">-</span><span class="dv">3</span>], <span class="at">btc.ci.95=</span>btc.ci,<span class="at">btr.ci.95=</span>btr.ci), </span>
<span id="cb123-2"><a href="bootstrapping-mlr-model.html#cb123-2" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Final Combined Inferential Statistics: p-values and Bootstrap CIs&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-112">Table 8.3: </span>Final Combined Inferential Statistics: p-values and Bootstrap CIs</caption>
<colgroup>
<col width="15%" />
<col width="8%" />
<col width="10%" />
<col width="18%" />
<col width="22%" />
<col width="22%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Estimate</th>
<th align="left">Std. Error</th>
<th align="left">Pr(&gt;|t|)</th>
<th align="left">btc.ci.95</th>
<th align="left">btr.ci.95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="left">3.5724</td>
<td align="left">0.0443</td>
<td align="left">0</td>
<td align="left">[ 3.4743 , 3.6596 ]</td>
<td align="left">[ 3.4848 , 3.6588 ]</td>
</tr>
<tr class="even">
<td align="left">HouseAge</td>
<td align="left">-0.0076</td>
<td align="left">0.001</td>
<td align="left">0</td>
<td align="left">[ -0.0097 , -0.0057 ]</td>
<td align="left">[ -0.0096 , -0.0055 ]</td>
</tr>
<tr class="odd">
<td align="left">NumConvenStores</td>
<td align="left">0.0275</td>
<td align="left">0.0049</td>
<td align="left">0</td>
<td align="left">[ 0.0166 , 0.0376 ]</td>
<td align="left">[ 0.0185 , 0.0373 ]</td>
</tr>
<tr class="even">
<td align="left">sale.year2013</td>
<td align="left">0.0806</td>
<td align="left">0.0244</td>
<td align="left">0.0011</td>
<td align="left">[ 0.0379 , 0.1228 ]</td>
<td align="left">[ 0.035 , 0.1291 ]</td>
</tr>
<tr class="odd">
<td align="left">Dist2MRT.kilo</td>
<td align="left">-0.1445</td>
<td align="left">0.0138</td>
<td align="left">0</td>
<td align="left">[ -0.1712 , -0.1153 ]</td>
<td align="left">[ -0.1721 , -0.119 ]</td>
</tr>
<tr class="even">
<td align="left">geo.groupTRUE</td>
<td align="left">0.1826</td>
<td align="left">0.0347</td>
<td align="left">0</td>
<td align="left">[ 0.1116 , 0.2614 ]</td>
<td align="left">[ 0.1124 , 0.2502 ]</td>
</tr>
</tbody>
</table>
<p>The above table shows that</p>
<ul>
<li>All three methods yield the same results in terms of the significance of individual explanatory variables. The reason is that the final working model does not have a serious violation of the model assumption.</li>
</ul>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="bootstrapping-mlr-model.html#cb124-1" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">cbind</span>(btc.wd, btr.wd), <span class="at">caption=</span><span class="st">&quot;width of the two bootstrap confidence intervals&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-113">Table 8.4: </span>width of the two bootstrap confidence intervals</caption>
<thead>
<tr class="header">
<th align="right">btc.wd</th>
<th align="right">btr.wd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.1852565</td>
<td align="right">0.1739648</td>
</tr>
<tr class="even">
<td align="right">0.0039574</td>
<td align="right">0.0041203</td>
</tr>
<tr class="odd">
<td align="right">0.0210309</td>
<td align="right">0.0188626</td>
</tr>
<tr class="even">
<td align="right">0.0849156</td>
<td align="right">0.0941134</td>
</tr>
<tr class="odd">
<td align="right">0.0558452</td>
<td align="right">0.0530981</td>
</tr>
<tr class="even">
<td align="right">0.1498495</td>
<td align="right">0.1378374</td>
</tr>
</tbody>
</table>
<ul>
<li>The widths of residual bootstrap and case-bootstrap confidence intervals are similar to each other. See the above table for the widths of each confidence interval.</li>
</ul>
<p>We see from the above table that the widths of residual-bootstrap and case-bootstrap confidence intervals are similar to each other.</p>
<p><br />
</p>
</div>
</div>
<div id="discussions-on-model-reporting" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Discussions on Model Reporting<a href="bootstrapping-mlr-model.html#discussions-on-model-reporting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have used different methods to perform regression analysis. The inferential results of all three major methods yield similar results. We chose the parametric model to report.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="bootstrapping-mlr-model.html#cb125-1" tabindex="-1"></a><span class="fu">kable</span>(cmtrx, <span class="at">caption =</span> <span class="st">&quot;Inferential Statistics of Final Model&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-114">Table 8.5: </span>Inferential Statistics of Final Model</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">3.5724</td>
<td align="right">0.0443</td>
<td align="right">80.5990</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">HouseAge</td>
<td align="right">-0.0076</td>
<td align="right">0.0010</td>
<td align="right">-7.4985</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">NumConvenStores</td>
<td align="right">0.0275</td>
<td align="right">0.0049</td>
<td align="right">5.5987</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">sale.year2013</td>
<td align="right">0.0806</td>
<td align="right">0.0244</td>
<td align="right">3.2963</td>
<td align="right">0.0011</td>
</tr>
<tr class="odd">
<td align="left">Dist2MRT.kilo</td>
<td align="right">-0.1445</td>
<td align="right">0.0138</td>
<td align="right">-10.5068</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">geo.groupTRUE</td>
<td align="right">0.1826</td>
<td align="right">0.0347</td>
<td align="right">5.2596</td>
<td align="right">0.0000</td>
</tr>
</tbody>
</table>
<p>Regression coefficients explain the correlation between log price and the corresponding explanatory variables. As an example, We explain the estimated regression coefficient of 0.1826. Let <span class="math inline">\(p_{TRUE}\)</span> be the mean price of a house in the region <code>TRUE</code> and <span class="math inline">\(p_{FALSE}\)</span> be the mean price of houses in the region <code>FALSE</code>. Then</p>
<p><span class="math display">\[
\log (p_{TRUE}) - \log(p_{FALSE}) = 0.1826  \to \log(p_{TRUE}/p_{FALSE}) = 0.1826 \to p_{TRUE} = 1.20p_{FALSE}
\]</span>
We re-express the above equation can be re-written as</p>
<p><span class="math display">\[
p_{TRUE} - p_{FALSE} = 0.206p_{FALSE} \to \frac{p_{TRUE}-p_{FALSE}}{p_{FALSE}} = 0.20 = 20\%.
\]</span></p>
<p>That is, the average house sales price in the <code>TRUE</code> region (top right corner on the map) is about 20% higher than that in the <code>FALSE</code> region. We can similarly interpret other regression coefficients.</p>
</div>
<div id="some-concluding-remarks" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Some Concluding Remarks<a href="bootstrapping-mlr-model.html#some-concluding-remarks" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="img05/w05-LetDataSpeak.png" width="80%" style="display: block; margin: auto;" /></p>
<div id="key-elements-in-storytelling" class="section level3 hasAnchor" number="8.7.1">
<h3><span class="header-section-number">8.7.1</span> Key Elements in Storytelling<a href="bootstrapping-mlr-model.html#key-elements-in-storytelling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Data storytelling is an effective way of communicating insights. It involves constructing a clear and relevant narrative in context, analyzing and visualizing data, and presenting findings effectively and persuasively. Data storytelling is an essential skill for statisticians.</p>
<p>Effective data storytelling involves three core elements: data, narrative, and visuals.</p>
<p><strong>Data</strong> is the foundation of every data story.</p>
<p><strong>Narrative</strong> is the structure of the data story. It’s not just about the words or context that are used to explain the information extracted from data, it is about how to organize the information into a meaningful and engaging story.</p>
<p><strong>Visuals</strong> are the scenes of the data story. When the data is complex, visualizing it in data charts helps the audience to <strong>see</strong> the <strong>information</strong> they might not otherwise see.</p>
</div>
<div id="title-and-heading-in-statistics-report" class="section level3 hasAnchor" number="8.7.2">
<h3><span class="header-section-number">8.7.2</span> Title and Heading in Statistics Report<a href="bootstrapping-mlr-model.html#title-and-heading-in-statistics-report" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Although headings and titles are similar, they are distinct: A title leads the entire document and captures its content in one or two phrases; a heading leads only a chapter or section and captures only the content of that chapter or section.</p>
<ul>
<li>A good <strong>title</strong> should be
<ul>
<li>descriptive,</li>
<li>Direct</li>
<li>Accurate</li>
<li>appropriate</li>
<li>concise</li>
<li>precise</li>
<li>unique and</li>
<li>should <strong>not</strong> be misleading.</li>
</ul></li>
<li>A good <strong>heading</strong> should be
<ul>
<li>Headings should be as long as it takes to communicate the content of the sections they head.</li>
<li>Higher-level headings often make do with a single word (e.g. <strong>Introduction</strong> or <strong>Methods</strong>), while lower-level headings are often longer.</li>
<li>Headings should be as descriptive as possible.</li>
<li>Headings should be unique.</li>
</ul></li>
</ul>
</div>
<div id="regression-modeling-and-reporting" class="section level3 hasAnchor" number="8.7.3">
<h3><span class="header-section-number">8.7.3</span> Regression Modeling and Reporting<a href="bootstrapping-mlr-model.html#regression-modeling-and-reporting" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are different approaches to regression modeling and reporting. We summarized the modeling process and techniques learned and suggested guidelines for reporting.</p>
<div id="modeling-workflow" class="section level4 hasAnchor" number="8.7.3.1">
<h4><span class="header-section-number">8.7.3.1</span> Modeling Workflow<a href="bootstrapping-mlr-model.html#modeling-workflow" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Linear regression workflow is summarized in the following chart</p>
<p><img src="img05/w05-LinearRegWorkflow.png" width="100%" style="display: block; margin: auto;" /></p>
<p>The specific model diagnostic methods and remedies to be included in the analysis are</p>
<ul>
<li><p>residual analysis - normality, constant variance, linearity of the regression equation, etc.</p></li>
<li><p>multicollinearity - variance inflation factor</p></li>
<li><p>potential transformation of the response variable - conventional and Box-cox methods</p></li>
<li><p>variable selection - expert-assisted variable selection (focusing on practical importance) and automatic variable selection (focusing on statistical significance).</p></li>
<li><p>non-parametric robust estimation of regression coefficients - two types of bootstrap methods.</p></li>
</ul>
</div>
<div id="reporting-guidelines" class="section level4 hasAnchor" number="8.7.3.2">
<h4><span class="header-section-number">8.7.3.2</span> Reporting Guidelines<a href="bootstrapping-mlr-model.html#reporting-guidelines" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have discussed the basic components of a statistics report. The following book chapter summarizes methods of writing and organizing statistical reports.</p>
<p><a href="https://instruction.bus.wisc.edu/jfrees/jfreesbooks/Regression%20Modeling/BookWebDec2010/Writing/Chap20FreesRegBook03May2009.pdf" class="uri">https://instruction.bus.wisc.edu/jfrees/jfreesbooks/Regression%20Modeling/BookWebDec2010/Writing/Chap20FreesRegBook03May2009.pdf</a></p>
<p>We have adopted the major components for our project reporting. Please review this document and pay attention to the sections related to how to report tables and figures.</p>
</div>
</div>
</div>
<div id="modeling-assignment" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Modeling Assignment<a href="bootstrapping-mlr-model.html#modeling-assignment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This assignment focuses on bootstrapping the multiple regression model you identified in your last assignment. You are expected to use both bootstrap sampling methods to find the confidence intervals for regression coefficients.</p>
<p>Please follow what did in the lecture note to do a similar analysis using your data and summarize the bootstrap analysis results. The mini-project report combines the results you obtained last week with this week’s bootstrap results.</p>
<p>The format of the report should have the following components using last and this week’s work as building blocks.</p>
<ul>
<li>Introduction
<ul>
<li>rationale of the project - research questions</li>
<li>description of data - sampling?</li>
<li>sufficient information for addressing the research questions</li>
</ul></li>
<li>Data preparation and exploratory analysis
<ul>
<li>create new variables based on existing variables?</li>
<li>discretizing continuous variable? combining categories of categorical variables?</li>
</ul></li>
<li>Model building
<ul>
<li>starting with a full model and performing residual analysis</li>
<li>identifying violations and finding remedies</li>
<li>need model transformations like the Cox-Cox procedure?</li>
<li>variable selection? -backward and forward selection, stepwise selection.</li>
<li>model selection using goodness-of-fit measures.</li>
<li>selection of the final model.</li>
</ul></li>
<li>Bootstrapping the final model
<ul>
<li>bootstrapping records</li>
<li>bootstrapping residuals of the final model obtained in the previous model</li>
</ul></li>
<li>Combining the results of the regular model and bootstrap results
<ul>
<li>Summarizing the results</li>
<li>Correct interpretations of the coefficients of the regression model.</li>
<li>Interpretation with caution if your response variable was transformed on a different scale.</li>
</ul></li>
<li>Summary and discussion
<ul>
<li>outline main findings</li>
<li>drawbacks and future improvements</li>
<li>recommendations on the applications of the model.</li>
</ul></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-linear-regression-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="simple-logistic-regression-model.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/pengdsci/STA321EB/edit/master/07-BootMLR.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["STA321EB.pdf", "STA321EB.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
